"""Success stories, blog extensions, countries, AI links and social links (bilingual)."""
from content import T

UI_MORE = [
    T("Read the story", "পুরো গল্প পড়ুন"),
    T("Success story", "সাফল্যের গল্প"),
    T("The challenge", "চ্যালেঞ্জ"),
    T("The solution", "সমাধান"),
    T("The results", "ফলাফল"),
    T("Modules used", "ব্যবহৃত মডিউল"),
    T("More success stories", "আরও সাফল্যের গল্প"),
    T("All success stories", "সব সাফল্যের গল্প"),
    T("Real results from travel businesses using TravelSuite ERP across Bangladesh, Malaysia and the GCC.",
      "বাংলাদেশ, মালয়েশিয়া ও GCC-তে TravelSuite ERP ব্যবহারকারী ট্রাভেল ব্যবসার আসল ফলাফল।"),
    T("Success stories — TravelSuite ERP", "সাফল্যের গল্প — TravelSuite ERP"),
    T("Time to go live", "চালু হতে সময়"),
    T("Location", "অবস্থান"),
    T("Business type", "ব্যবসার ধরন"),
    T("Website", "ওয়েবসাইট"),
    T("Table of contents", "সূচিপত্র"),
    T("Key takeaways", "মূল কথা"),
    T("Frequently asked questions", "সচরাচর জিজ্ঞাসা"),
    T("About the author", "লেখক সম্পর্কে"),
    T("The TravelSuite team builds travel booking and ERP software for agencies in Bangladesh, Malaysia, the GCC and the USA.",
      "TravelSuite টিম বাংলাদেশ, মালয়েশিয়া, GCC ও যুক্তরাষ্ট্রের এজেন্সির জন্য ট্রাভেল বুকিং ও ERP সফটওয়্যার তৈরি করে।"),
    T("Featured article", "বিশেষ লেখা"),
    T("Categories", "বিভাগ"),
    T("articles", "টি লেখা"),
    T("Reading progress", "পড়ার অগ্রগতি"),
    T("Where we work", "যেখানে আমরা কাজ করি"),
    T("Serving travel businesses across the GCC, Southeast Asia and beyond", "GCC, দক্ষিণ-পূর্ব এশিয়া ও তার বাইরে ট্রাভেল ব্যবসার পাশে"),
    T("Local teams in the USA, Malaysia and Bangladesh support agencies in every market we serve.",
      "যুক্তরাষ্ট্র, মালয়েশিয়া ও বাংলাদেশে আমাদের স্থানীয় টিম প্রতিটি মার্কেটের এজেন্সিকে সাপোর্ট দেয়।"),
    T("Office", "অফিস"),
    T("Our offices", "আমাদের অফিস"),
    T("Markets we serve", "যেসব মার্কেটে কাজ করি"),
    T("Ask any AI about TravelSuite ERP", "যেকোনো AI-কে TravelSuite ERP সম্পর্কে জিজ্ঞাসা করুন"),
    T("Get an instant, independent summary of our platform from your favourite AI assistant.",
      "আপনার পছন্দের AI অ্যাসিস্ট্যান্ট থেকে আমাদের প্ল্যাটফর্মের তাৎক্ষণিক ও নিরপেক্ষ সারাংশ নিন।"),
    T("Follow us", "আমাদের ফলো করুন"),
    T("Secure international payments", "নিরাপদ আন্তর্জাতিক পেমেন্ট"),
    T("GCC", "GCC"),
    T("Southeast Asia", "দক্ষিণ-পূর্ব এশিয়া"),
    T("South Asia", "দক্ষিণ এশিয়া"),
    T("North America", "উত্তর আমেরিকা"),
]

COUNTRIES = [
    dict(code="sa", name=T("Saudi Arabia", "সৌদি আরব"), region="GCC", office=False),
    dict(code="ae", name=T("United Arab Emirates", "সংযুক্ত আরব আমিরাত"), region="GCC", office=False),
    dict(code="qa", name=T("Qatar", "কাতার"), region="GCC", office=False),
    dict(code="kw", name=T("Kuwait", "কুয়েত"), region="GCC", office=False),
    dict(code="om", name=T("Oman", "ওমান"), region="GCC", office=False),
    dict(code="bh", name=T("Bahrain", "বাহরাইন"), region="GCC", office=False),
    dict(code="my", name=T("Malaysia", "মালয়েশিয়া"), region="Southeast Asia", office=True),
    dict(code="bd", name=T("Bangladesh", "বাংলাদেশ"), region="South Asia", office=True),
    dict(code="us", name=T("United States", "যুক্তরাষ্ট্র"), region="North America", office=True),
]

AI_PROMPT = ("What is TravelSuite ERP (travelsuiteerp.com)? Summarize its features for travel agencies, "
             "Hajj & Umrah operators and B2B consolidators, and who it is best for.")
AI_LINKS = [
    ("ChatGPT", "openai", "https://chatgpt.com/?q="),
    ("Claude", "claude", "https://claude.ai/new?q="),
    ("Perplexity", "perplexity", "https://www.perplexity.ai/search?q="),
    ("Google AI", "googlegemini", "https://www.google.com/search?udm=50&q="),
]

# Profile URLs are placeholders until the real handles are confirmed.
SOCIAL = [
    ("Facebook", "facebook", "https://www.facebook.com/travelsuiteerp"),
    ("Instagram", "instagram", "https://www.instagram.com/travelsuiteerp"),
    ("LinkedIn", "linkedin", "https://www.linkedin.com/company/travelsuiteerp"),
    ("YouTube", "youtube", "https://www.youtube.com/@travelsuiteerp"),
    ("X", "x", "https://x.com/travelsuiteerp"),
    ("WhatsApp", "whatsapp", "https://wa.me/8801325277120"),
]

PAYMENTS = [("Visa", "visa"), ("Mastercard", "mastercard"), ("American Express", "americanexpress"),
            ("PayPal", "paypal"), ("Stripe", "stripe"), ("Apple Pay", "applepay"), ("Google Pay", "googlepay")]

SUCCESS = [
    dict(slug="umrah-portal", shot="umrah", url="umrah-portal", type="Hajj & Umrah operator", location="Dhaka, Bangladesh",
         chips=["Hajj & Umrah", "Visa", "Finance"], metric="2,400+ pilgrims managed in one season", golive=T("14 days", "১৪ দিন"),
         headline=T("How a Dhaka Umrah operator managed 2,400 pilgrims in one season without spreadsheets",
                    "যেভাবে ঢাকার এক উমরাহ অপারেটর স্প্রেডশিট ছাড়াই এক মৌসুমে ২,৪০০ হাজি পরিচালনা করেছে"),
         intro=T("A family-run Hajj and Umrah agency moved pilgrim registration, packages and instalments into TravelSuite ERP before its busiest season.",
                 "একটি পারিবারিক হজ ও উমরাহ এজেন্সি তাদের ব্যস্ততম মৌসুমের আগে হাজি রেজিস্ট্রেশন, প্যাকেজ ও কিস্তির হিসাব TravelSuite ERP-এ নিয়ে আসে।"),
         challenge=T("Pilgrim lists lived in several Excel files, instalments were tracked in a notebook and room allocation was done by hand the night before departure. Staff spent more time reconciling lists than serving pilgrims.",
                     "হাজির তালিকা ছিল কয়েকটি Excel ফাইলে, কিস্তির হিসাব খাতায়, আর রুম বণ্টন হতো যাত্রার আগের রাতে হাতে। স্টাফরা হাজিদের সেবার চেয়ে তালিকা মেলাতেই বেশি সময় দিতেন।"),
         solution=[T("Pilgrim register with passport, photo and documents", "পাসপোর্ট, ছবি ও ডকুমেন্টসহ হাজি রেজিস্টার"),
                   T("Packages linking flights, Makkah and Madinah hotels and transport", "ফ্লাইট, মক্কা ও মদিনার হোটেল এবং ট্রান্সপোর্ট যুক্ত প্যাকেজ"),
                   T("Instalment schedules with WhatsApp reminders", "WhatsApp রিমাইন্ডারসহ কিস্তির সূচি"),
                   T("Group and room allocation exported for hotels", "হোটেলের জন্য এক্সপোর্টযোগ্য গ্রুপ ও রুম বণ্টন")],
         results=[("2,400+", T("pilgrims managed in one season", "এক মৌসুমে পরিচালিত হাজি")),
                  ("3×", T("more pilgrims than the previous season", "আগের মৌসুমের চেয়ে বেশি হাজি")),
                  ("98%", T("instalments collected on time", "সময়মতো আদায় হওয়া কিস্তি"))],
         modules=["hajj", "visa", "invoices", "finance"],
         quote="We used to manage Umrah groups in Excel and payments in a notebook. Now every pilgrim, payment and message is in one place.",
         person="Managing Director"),
    dict(slug="b2b-fares", shot="b2b", url="b2b-fares", type="B2B ticketing consolidator", location="Chattogram, Bangladesh",
         chips=["Flights", "B2B portal", "Agent ledger"], metric="180 sub-agents on one portal", golive=T("10 days", "১০ দিন"),
         headline=T("A Chattogram consolidator grew to 180 sub-agents with a self-service B2B portal",
                    "সেলফ-সার্ভিস B2B পোর্টাল দিয়ে চট্টগ্রামের এক কনসোলিডেটর ১৮০ সাব-এজেন্টে পৌঁছেছে"),
         intro=T("A ticketing consolidator replaced phone and WhatsApp bookings with an agent portal that controls credit automatically.",
                 "এক টিকিটিং কনসোলিডেটর ফোন ও WhatsApp বুকিংয়ের বদলে এমন এজেন্ট পোর্টাল চালু করেছে, যা অটোমেটিক ক্রেডিট নিয়ন্ত্রণ করে।"),
         challenge=T("Every sub-agent booking came through a phone call or WhatsApp message, credit was given informally, and agent statements took days to prepare at month-end.",
                     "প্রতিটি সাব-এজেন্ট বুকিং আসত ফোন বা WhatsApp-এ, ক্রেডিট দেওয়া হতো অনানুষ্ঠানিকভাবে, আর মাস শেষে এজেন্ট স্টেটমেন্ট তৈরিতে কয়েক দিন লাগত।"),
         solution=[T("B2B portal with net fares and instant ticketing", "নেট ভাড়া ও সাথে সাথে টিকিটিংসহ B2B পোর্টাল"),
                   T("Credit limits and deposit wallets per agent", "প্রতি এজেন্টের ক্রেডিট লিমিট ও ডিপোজিট ওয়ালেট"),
                   T("Markups by agent group and airline", "এজেন্ট গ্রুপ ও এয়ারলাইন অনুযায়ী মার্কআপ"),
                   T("Agent ledgers and statements on demand", "চাহিবামাত্র এজেন্ট লেজার ও স্টেটমেন্ট")],
         results=[("180", T("active sub-agents", "সক্রিয় সাব-এজেন্ট")),
                  ("+140", T("new agents in the first year", "প্রথম বছরে নতুন এজেন্ট")),
                  ("0", T("extra accounts staff hired", "নতুন অ্যাকাউন্টস স্টাফ নিয়োগ"))],
         modules=["b2b", "flights", "finance", "reports"],
         quote="The B2B portal with agent credit limits let us grow our sub-agent network without hiring more accounts staff.",
         person="Founder"),
    dict(slug="tours-bd", shot="tours", url="tours-bd", type="Tour operator", location="Sylhet, Bangladesh",
         chips=["Tour packages", "Website", "Omnichannel"], metric="40% of bookings now online", golive=T("12 days", "১২ দিন"),
         headline=T("A Sylhet tour operator now takes 40% of bookings online", "সিলেটের এক ট্যুর অপারেটর এখন ৪০% বুকিং অনলাইনে নেয়"),
         intro=T("A domestic tour operator launched a booking website and a shared WhatsApp inbox connected to its packages and CRM.",
                 "একটি দেশীয় ট্যুর অপারেটর প্যাকেজ ও CRM-এর সাথে যুক্ত বুকিং ওয়েবসাইট ও শেয়ার্ড WhatsApp ইনবক্স চালু করেছে।"),
         challenge=T("Inquiries arrived on Facebook and personal phones, itineraries were retyped in Word for each customer, and popular departures were sometimes oversold.",
                     "ইনকোয়ারি আসত Facebook ও ব্যক্তিগত ফোনে, প্রতিটি কাস্টমারের জন্য Word-এ নতুন করে ভ্রমণসূচি লেখা হতো, আর জনপ্রিয় ডিপারচারে মাঝে মাঝে সিট বেশি বিক্রি হয়ে যেত।"),
         solution=[T("Package builder with day-by-day itineraries", "দিনভিত্তিক ভ্রমণসূচিসহ প্যাকেজ বিল্ডার"),
                   T("Booking website with online payment", "অনলাইন পেমেন্টসহ বুকিং ওয়েবসাইট"),
                   T("Shared inbox for WhatsApp, Messenger and Instagram", "WhatsApp, Messenger ও Instagram-এর শেয়ার্ড ইনবক্স"),
                   T("Seat inventory per departure", "প্রতি ডিপারচারের সিট ইনভেন্টরি")],
         results=[("40%", T("of bookings made online", "বুকিং অনলাইনে")),
                  (T("< 5 min", "< ৫ মিনিট"), T("average reply time", "গড় উত্তরের সময়")),
                  ("0", T("oversold departures since launch", "চালুর পর থেকে বেশি বিক্রি হওয়া ডিপারচার"))],
         modules=["tours", "website", "omnichannel", "crm"],
         quote="WhatsApp, Messenger and Instagram chats land in one inbox and turn into CRM leads. Nobody misses an inquiry now.",
         person="Sales Manager"),
    dict(slug="fly-gulf", shot="gulf", url="fly-gulf", type="Online travel agency", location="Dubai, UAE",
         chips=["Flights", "Hotels", "B2C"], metric="Live in 12 days", golive=T("12 days", "১২ দিন"),
         headline=T("A Dubai OTA launched its booking site in 12 days with international payments",
                    "আন্তর্জাতিক পেমেন্টসহ দুবাইয়ের এক OTA ১২ দিনে বুকিং সাইট চালু করেছে"),
         intro=T("A new online travel agency in the UAE needed flights, hotels and card payments live before the winter season.",
                 "সংযুক্ত আরব আমিরাতের একটি নতুন অনলাইন ট্রাভেল এজেন্সির শীত মৌসুমের আগেই ফ্লাইট, হোটেল ও কার্ড পেমেন্ট চালু করা দরকার ছিল।"),
         challenge=T("The founders had supplier contracts but no booking website, no payment gateway and no back office to fulfil orders.",
                     "প্রতিষ্ঠাতাদের সাপ্লায়ার চুক্তি ছিল, কিন্তু বুকিং ওয়েবসাইট, পেমেন্ট গেটওয়ে বা অর্ডার সম্পন্ন করার ব্যাক অফিস ছিল না।"),
         solution=[T("Branded B2C website on their own domain", "নিজের ডোমেইনে ব্র্যান্ডেড B2C ওয়েবসাইট"),
                   T("Stripe, Apple Pay and Google Pay at checkout", "চেকআউটে Stripe, Apple Pay ও Google Pay"),
                   T("Flight and hotel supplier connections", "ফ্লাইট ও হোটেল সাপ্লায়ার সংযোগ"),
                   T("AI assistant answering questions after hours", "অফিস সময়ের পরে প্রশ্নের উত্তর দেওয়া AI অ্যাসিস্ট্যান্ট")],
         results=[("12", T("days from contract to launch", "চুক্তি থেকে চালু পর্যন্ত দিন")),
                  ("3", T("currencies on one site: AED, USD, BDT", "মুদ্রা এক সাইটে: AED, USD, BDT")),
                  ("24/7", T("AI replies to customer questions", "কাস্টমারের প্রশ্নে AI উত্তর"))],
         modules=["website", "b2b", "flights", "ai"],
         quote="Setup, branding and payment gateway were done in under two weeks, and the support team answers quickly on WhatsApp.",
         person="CEO"),
    dict(slug="visa-desk", shot="visa", url="visa-desk", type="Visa processing centre", location="Dhaka, Bangladesh",
         chips=["Visa", "CRM", "Help desk"], metric="Every file tracked stage by stage", golive=T("7 days", "৭ দিন"),
         headline=T("A Dhaka visa centre cut status calls by tracking every file stage by stage",
                    "প্রতিটি ফাইল ধাপে ধাপে ট্র্যাক করে ঢাকার এক ভিসা সেন্টার স্ট্যাটাস জানতে ফোন কমিয়েছে"),
         intro=T("A busy visa processing centre moved hundreds of monthly applications from paper files to tracked digital files.",
                 "একটি ব্যস্ত ভিসা প্রসেসিং সেন্টার মাসে শত শত আবেদন কাগজের ফাইল থেকে ট্র্যাক করা ডিজিটাল ফাইলে নিয়ে এসেছে।"),
         challenge=T("Customers called several times a day asking for status, documents were sometimes missing at submission and nobody could see which staff member owned each file.",
                     "কাস্টমাররা দিনে কয়েকবার ফোন করে স্ট্যাটাস জানতে চাইতেন, জমার সময় মাঝে মাঝে ডকুমেন্ট বাদ পড়ত, আর কোন ফাইল কোন স্টাফের দায়িত্বে তা কেউ দেখতে পেতেন না।"),
         solution=[T("Country and visa-type checklists", "দেশ ও ভিসার ধরন অনুযায়ী চেকলিস্ট"),
                   T("Stages with responsible staff for every file", "প্রতিটি ফাইলের দায়িত্বপ্রাপ্ত স্টাফসহ ধাপ"),
                   T("Automatic SMS and WhatsApp status updates", "অটোমেটিক SMS ও WhatsApp স্ট্যাটাস আপডেট"),
                   T("Help desk tickets linked to applications", "আবেদনের সাথে যুক্ত হেল্প ডেস্ক টিকিট")],
         results=[("60%", T("fewer status calls", "কম স্ট্যাটাস ফোন")),
                  ("100%", T("of files with a named owner", "ফাইলের নির্দিষ্ট দায়িত্বপ্রাপ্ত")),
                  ("7", T("days to go live", "দিনে চালু"))],
         modules=["visa", "crm", "helpdesk", "tasks"],
         quote="Our visa team tracks every file stage by stage, and customers get updates automatically. Calls asking for status dropped sharply.",
         person="Operations Head"),
    dict(slug="corp-travel", shot="corp", url="corp-travel", type="Corporate travel desk", location="Kuala Lumpur, Malaysia",
         chips=["Flights", "Hotels", "Approvals"], metric="Monthly billing automated", golive=T("14 days", "১৪ দিন"),
         headline=T("A Kuala Lumpur travel desk automated approvals and monthly billing for corporate clients",
                    "কুয়ালালামপুরের এক ট্রাভেল ডেস্ক কর্পোরেট ক্লায়েন্টদের অনুমোদন ও মাসিক বিলিং অটোমেট করেছে"),
         intro=T("A corporate travel agency serving regional companies replaced email approvals and manual invoices with workflows and reports.",
                 "আঞ্চলিক কোম্পানিগুলোকে সেবা দেওয়া একটি কর্পোরেট ট্রাভেল এজেন্সি ইমেইল অনুমোদন ও হাতে তৈরি ইনভয়েসের বদলে ওয়ার্কফ্লো ও রিপোর্ট চালু করেছে।"),
         challenge=T("Approvals were chased over email, monthly invoices were compiled by hand from dozens of bookings, and clients kept asking for spend reports.",
                     "অনুমোদনের জন্য ইমেইলে পেছনে ছুটতে হতো, মাসিক ইনভয়েস কয়েক ডজন বুকিং থেকে হাতে তৈরি হতো, আর ক্লায়েন্টরা বারবার খরচের রিপোর্ট চাইতেন।"),
         solution=[T("Approval workflow for every trip request", "প্রতিটি ট্রিপ অনুরোধের অনুমোদন ধাপ"),
                   T("Company accounts with monthly billing", "মাসিক বিলিংসহ কোম্পানি অ্যাকাউন্ট"),
                   T("Spend reports by department and cost centre", "বিভাগ ও কস্ট সেন্টার অনুযায়ী খরচের রিপোর্ট"),
                   T("Tasks for ticketing and changes", "টিকিটিং ও পরিবর্তনের টাস্ক")],
         results=[("1", T("invoice per client per month", "প্রতি ক্লায়েন্টে মাসে ইনভয়েস")),
                  ("96%", T("of trips booked within policy", "পলিসি মেনে বুক হওয়া ট্রিপ")),
                  (T("2 days", "২ দিন"), T("saved every month-end", "প্রতি মাস শেষে সাশ্রয়"))],
         modules=["flights", "hotels", "invoices", "reports"],
         quote="Month-end used to take a week of matching tickets with bank statements. Now the ledgers are ready on the first day.",
         person="Finance Manager"),
]

# Extra sections, key takeaways and FAQs for blog posts
BLOG_EXTRA = {
    "digitize-hajj-umrah-agency": dict(
        takeaways=[T("Keep one pilgrim register as the single source of truth", "একটি হাজি রেজিস্টারকে একমাত্র নির্ভরযোগ্য উৎস রাখুন"),
                   T("Link packages to flights, hotels and transport", "প্যাকেজকে ফ্লাইট, হোটেল ও ট্রান্সপোর্টের সাথে যুক্ত করুন"),
                   T("Automate instalment reminders", "কিস্তির রিমাইন্ডার অটোমেট করুন")],
        blocks=[("h2", T("Allocate groups and rooms early", "আগে থেকেই গ্রুপ ও রুম বণ্টন করুন")),
                ("p", T("Group pilgrims by departure and assign rooms as soon as hotels are confirmed. Exported lists for hotels, transport companies and guides prevent last-minute confusion in Makkah and Madinah.",
                        "যাত্রা অনুযায়ী হাজিদের গ্রুপ করুন এবং হোটেল কনফার্ম হলেই রুম বরাদ্দ দিন। হোটেল, ট্রান্সপোর্ট কোম্পানি ও গাইডের জন্য এক্সপোর্ট করা তালিকা মক্কা ও মদিনায় শেষ মুহূর্তের বিভ্রান্তি ঠেকায়।")),
                ("h2", T("Track visas and documents per pilgrim", "প্রতি হাজির ভিসা ও ডকুমেন্ট ট্র্যাক করুন")),
                ("p", T("A checklist on every file shows which documents are missing and where each visa stands. Managers can filter the register to see only pilgrims with pending items.",
                        "প্রতিটি ফাইলের চেকলিস্ট দেখায় কোন ডকুমেন্ট বাকি এবং প্রতিটি ভিসা কোন অবস্থায়। ম্যানেজার রেজিস্টার ফিল্টার করে শুধু বাকি থাকা হাজিদের দেখতে পারেন।")),
                ("h2", T("Measure the season", "মৌসুমের হিসাব মাপুন")),
                ("p", T("At the end of the season, compare collections, supplier costs and expenses per package. These numbers guide pricing for the next season.",
                        "মৌসুম শেষে প্রতিটি প্যাকেজের আদায়, সাপ্লায়ার খরচ ও ব্যয় তুলনা করুন। এই সংখ্যাগুলোই পরের মৌসুমের মূল্য নির্ধারণে পথ দেখায়।"))],
        faqs=[(T("How long does it take to move an Umrah agency online?", "উমরাহ এজেন্সি অনলাইনে আনতে কত সময় লাগে?"),
               T("Most agencies are running within two weeks, including importing existing pilgrim lists.", "বর্তমান হাজির তালিকা ইমপোর্টসহ বেশিরভাগ এজেন্সি দুই সপ্তাহের মধ্যে চালু হয়।")),
              (T("Can pilgrims pay online?", "হাজিরা কি অনলাইনে পরিশোধ করতে পারবেন?"),
               T("Yes. Send payment links for card, PayPal or Apple Pay, or record bank and cash payments.", "হ্যাঁ। কার্ড, PayPal বা Apple Pay-এর পেমেন্ট লিংক পাঠান, অথবা ব্যাংক ও নগদ পেমেন্ট রেকর্ড করুন।"))]),
    "b2b-agent-credit-limits": dict(
        takeaways=[T("Give every agent a clear credit limit", "প্রতিটি এজেন্টকে স্পষ্ট ক্রেডিট লিমিট দিন"),
                   T("Use deposit wallets to collect cash before ticketing", "টিকিটিংয়ের আগে টাকা পেতে ডিপোজিট ওয়ালেট ব্যবহার করুন"),
                   T("Review aging reports every month", "প্রতি মাসে এজিং রিপোর্ট পর্যালোচনা করুন")],
        blocks=[("h2", T("Automate statements", "স্টেটমেন্ট অটোমেট করুন")),
                ("p", T("When every ticket posts to the agent's ledger automatically, statements are always ready. Agents see their balance in the portal, which reduces disputes and speeds up payment.",
                        "প্রতিটি টিকিট অটোমেটিক এজেন্টের লেজারে পোস্ট হলে স্টেটমেন্ট সবসময় প্রস্তুত থাকে। এজেন্টরা পোর্টালে ব্যালান্স দেখেন, ফলে বিরোধ কমে এবং দ্রুত পেমেন্ট আসে।")),
                ("h2", T("Accept international payments", "আন্তর্জাতিক পেমেন্ট নিন")),
                ("p", T("Agents in the GCC and Malaysia often prefer to top up by card. Accepting Visa, Mastercard, PayPal and Stripe alongside bank transfer makes deposits faster.",
                        "GCC ও মালয়েশিয়ার এজেন্টরা প্রায়ই কার্ডে টাকা যোগ করতে পছন্দ করেন। ব্যাংক ট্রান্সফারের পাশাপাশি Visa, Mastercard, PayPal ও Stripe নিলে ডিপোজিট দ্রুত হয়।"))],
        faqs=[(T("What is a good starting credit limit?", "শুরুতে কত ক্রেডিট লিমিট ভালো?"),
               T("Many consolidators start with one week of an agent's average sales and adjust after three months of history.", "অনেক কনসোলিডেটর এজেন্টের এক সপ্তাহের গড় বিক্রি দিয়ে শুরু করেন এবং তিন মাসের ইতিহাস দেখে বদলান।")),
              (T("Can limits change automatically?", "লিমিট কি অটোমেটিক বদলাতে পারে?"),
               T("Limits are set by your team, guided by the aging and payment history reports.", "লিমিট আপনার টিম ঠিক করে, এজিং ও পেমেন্ট ইতিহাসের রিপোর্ট দেখে।"))]),
    "double-entry-accounting-travel": dict(
        takeaways=[T("A cash book cannot show real profit", "ক্যাশ বুক আসল মুনাফা দেখাতে পারে না"),
                   T("Record receivables and payables on every booking", "প্রতিটি বুকিংয়ে প্রাপ্য ও দেনা রেকর্ড করুন"),
                   T("Measure profit per booking, service and agent", "বুকিং, সার্ভিস ও এজেন্ট অনুযায়ী মুনাফা মাপুন")],
        blocks=[("h2", T("Handle multiple currencies correctly", "বহু মুদ্রা সঠিকভাবে সামলান")),
                ("p", T("Agencies selling in SAR, AED, MYR or USD face exchange differences between booking and payment. Double-entry accounting records those gains and losses so they do not hide inside your margin.",
                        "SAR, AED, MYR বা USD-তে বিক্রি করা এজেন্সির বুকিং ও পেমেন্টের মধ্যে বিনিময় পার্থক্য হয়। ডাবল-এন্ট্রি অ্যাকাউন্টিং সেই লাভ-ক্ষতি রেকর্ড করে, যাতে তা আপনার মুনাফার ভেতরে লুকিয়ে না থাকে।")),
                ("h2", T("Reconcile with BSP and suppliers", "BSP ও সাপ্লায়ারের সাথে মিলান")),
                ("p", T("When tickets and supplier bills post automatically, BSP and supplier statements can be matched line by line in minutes instead of days.",
                        "টিকিট ও সাপ্লায়ার বিল অটোমেটিক পোস্ট হলে BSP ও সাপ্লায়ার স্টেটমেন্ট দিনের বদলে কয়েক মিনিটে লাইন ধরে মেলানো যায়।"))],
        faqs=[(T("Do I need an accountant to use it?", "ব্যবহার করতে কি অ্যাকাউন্ট্যান্ট লাগবে?"),
               T("Daily work is automatic; an accountant reviews reports and closes the period.", "দৈনন্দিন কাজ অটোমেটিক; অ্যাকাউন্ট্যান্ট রিপোর্ট দেখেন ও সময়কাল বন্ধ করেন।")),
              (T("Can I export to my existing accounting software?", "বর্তমান অ্যাকাউন্টিং সফটওয়্যারে কি এক্সপোর্ট করা যায়?"),
               T("Yes. Export journals to Excel, QuickBooks or Xero.", "হ্যাঁ। জার্নাল Excel, QuickBooks বা Xero-তে এক্সপোর্ট করুন।"))]),
    "whatsapp-for-travel-agencies": dict(
        takeaways=[T("Move customer chats off personal phones", "কাস্টমার চ্যাট ব্যক্তিগত ফোন থেকে সরিয়ে আনুন"),
                   T("Assign every conversation to one owner", "প্রতিটি কথোপকথনের একজন দায়িত্বপ্রাপ্ত রাখুন"),
                   T("Turn good chats into CRM leads", "ভালো চ্যাটকে CRM লিডে রূপ দিন")],
        blocks=[("h2", T("Use templates for confirmations", "কনফার্মেশনের জন্য টেমপ্লেট ব্যবহার করুন")),
                ("p", T("Approved WhatsApp templates let you send booking confirmations, payment reminders and travel documents automatically, even outside the 24-hour chat window.",
                        "অনুমোদিত WhatsApp টেমপ্লেট দিয়ে বুকিং কনফার্মেশন, পেমেন্ট রিমাইন্ডার ও ভ্রমণ ডকুমেন্ট অটোমেটিক পাঠানো যায়, এমনকি ২৪ ঘণ্টার চ্যাট সময়ের বাইরেও।")),
                ("h2", T("Bring Messenger and Instagram together", "Messenger ও Instagram একসাথে আনুন")),
                ("p", T("Customers in the GCC and Malaysia often message on Instagram, while Bangladeshi customers prefer Messenger and WhatsApp. One inbox covers them all.",
                        "GCC ও মালয়েশিয়ার কাস্টমাররা প্রায়ই Instagram-এ মেসেজ দেন, আর বাংলাদেশি কাস্টমাররা পছন্দ করেন Messenger ও WhatsApp। একটি ইনবক্স সবগুলোই সামলায়।"))],
        faqs=[(T("Is the WhatsApp Business app enough?", "WhatsApp Business অ্যাপ কি যথেষ্ট?"),
               T("For one person, yes. For a team sharing one number, you need the WhatsApp Business Platform connected to a shared inbox.", "একজনের জন্য হ্যাঁ। একটি নম্বর শেয়ার করা টিমের জন্য শেয়ার্ড ইনবক্সে যুক্ত WhatsApp Business Platform লাগবে।")),
              (T("Can I keep my existing number?", "বর্তমান নম্বর কি রাখা যাবে?"),
               T("Usually yes. The number is migrated to the WhatsApp Business Platform during setup.", "সাধারণত হ্যাঁ। সেটআপের সময় নম্বরটি WhatsApp Business Platform-এ স্থানান্তর করা হয়।"))]),
    "ai-trip-planners": dict(
        takeaways=[T("AI writes the first draft in seconds", "AI সেকেন্ডে প্রথম খসড়া লেখে"),
                   T("Consultants check prices and suppliers", "কনসালট্যান্টরা মূল্য ও সাপ্লায়ার যাচাই করেন"),
                   T("Use AI to qualify leads after hours", "অফিস সময়ের পরে লিড যাচাইয়ে AI ব্যবহার করুন")],
        blocks=[("h2", T("Getting started with AI safely", "নিরাপদে AI দিয়ে শুরু")),
                ("p", T("Start with low-risk tasks such as answering common questions and drafting itineraries. Review AI replies for the first weeks, then widen what it handles as you gain confidence.",
                        "সাধারণ প্রশ্নের উত্তর ও ভ্রমণসূচির খসড়ার মতো কম ঝুঁকির কাজ দিয়ে শুরু করুন। প্রথম কয়েক সপ্তাহ AI-এর উত্তর পর্যালোচনা করুন, আস্থা বাড়লে দায়িত্ব বাড়ান।")),
                ("h2", T("Measure the impact", "প্রভাব মাপুন")),
                ("p", T("Track reply times, leads qualified after hours and time saved per itinerary. These numbers show whether AI is paying for itself.",
                        "উত্তরের সময়, অফিস সময়ের পরে যাচাই হওয়া লিড এবং প্রতি ভ্রমণসূচিতে বাঁচানো সময় ট্র্যাক করুন। এই সংখ্যাগুলোই দেখায় AI নিজের খরচ তুলছে কিনা।"))],
        faqs=[(T("Will AI replace travel consultants?", "AI কি ট্রাভেল কনসালট্যান্টদের জায়গা নেবে?"),
               T("No. It handles repetitive drafting and questions so consultants can focus on selling and service.", "না। এটি বারবার করা খসড়া ও প্রশ্ন সামলায়, তাই কনসালট্যান্টরা বিক্রি ও সেবায় মন দিতে পারেন।")),
              (T("Which languages does the AI support?", "AI কোন কোন ভাষা সাপোর্ট করে?"),
               T("English, Arabic, Bangla, Malay and many others.", "ইংরেজি, আরবি, বাংলা, মালয়সহ আরও অনেক।"))]),
    "choosing-a-travel-erp": dict(
        takeaways=[T("List every service and workflow you run today", "আজ যেসব সার্ভিস ও কাজ চালান তার তালিকা করুন"),
                   T("Check payments for every market you serve", "প্রতিটি মার্কেটের পেমেন্ট মাধ্যম যাচাই করুন"),
                   T("Ask for a demo with your own data", "নিজের ডেটা দিয়ে ডেমো চান")],
        blocks=[("h2", T("Think about every market you sell to", "যেসব মার্কেটে বিক্রি করেন সবগুলো বিবেচনা করুন")),
                ("p", T("If you sell to customers in the GCC, Malaysia or the USA, check that the system supports their currencies, languages and payment methods such as Visa, Mastercard, PayPal, Stripe and Apple Pay.",
                        "GCC, মালয়েশিয়া বা যুক্তরাষ্ট্রের কাস্টমারের কাছে বিক্রি করলে সিস্টেম তাদের মুদ্রা, ভাষা এবং Visa, Mastercard, PayPal, Stripe ও Apple Pay-এর মতো পেমেন্ট মাধ্যম সাপোর্ট করে কিনা দেখুন।")),
                ("h2", T("Plan the switch", "পরিবর্তনের পরিকল্পনা করুন")),
                ("p", T("Pick a quiet period, import customers and balances first, train staff in short sessions and run old and new systems side by side for one or two weeks.",
                        "একটি কম ব্যস্ত সময় বেছে নিন, আগে কাস্টমার ও ব্যালান্স ইমপোর্ট করুন, ছোট ছোট সেশনে স্টাফদের ট্রেনিং দিন এবং এক-দুই সপ্তাহ পুরনো ও নতুন সিস্টেম পাশাপাশি চালান।"))],
        faqs=[(T("How much does a travel ERP cost?", "ট্রাভেল ERP-এর খরচ কত?"),
               T("Cloud plans usually start at a monthly fee, while self-hosted licenses are a one-time payment. See our pricing page for current plans.", "ক্লাউড প্ল্যান সাধারণত মাসিক ফি দিয়ে শুরু, আর নিজস্ব সার্ভারের লাইসেন্স এককালীন। বর্তমান প্ল্যান দেখতে আমাদের মূল্য পেজ দেখুন।")),
              (T("Can I try before I buy?", "কেনার আগে কি চেষ্টা করে দেখা যায়?"),
               T("Yes. Book a guided demo with sample data based on your workflows.", "হ্যাঁ। আপনার কাজের ধরন অনুযায়ী স্যাম্পল ডেটাসহ গাইডেড ডেমো বুক করুন।"))]),
}
