"""Site content used by build.py to generate feature, solution, blog and legal pages.

Text written as T("English", "বাংলা") is bilingual: the English goes into the page and the
pair is added to the generated translation file (assets/js/i18n-data.js).
Plain strings are English-only here and must already have a translation in assets/js/i18n.js.
"""


def T(en, bn):
    return (en, bn)


# ---------------------------------------------------------------------------
# Shared interface text
# ---------------------------------------------------------------------------
UI = [
    T("Home", "হোম"),
    T("Learn more", "বিস্তারিত দেখুন"),
    T("Key capabilities", "মূল সক্ষমতা"),
    T("How it works", "কীভাবে কাজ করে"),
    T("Why agencies use it", "এজেন্সিগুলো কেন ব্যবহার করে"),
    T("Related features", "সম্পর্কিত ফিচার"),
    T("All features", "সব ফিচার"),
    T("Works with every TravelSuite module", "TravelSuite-এর প্রতিটি মডিউলের সাথে যুক্ত"),
    T("Bookings, customers, payments and accounts stay in one database, so this module shares data with everything else automatically.",
      "বুকিং, কাস্টমার, পেমেন্ট ও হিসাব একই ডেটাবেসে থাকে, তাই এই মডিউল অন্য সবকিছুর সাথে অটোমেটিক ডেটা শেয়ার করে।"),
    T("Solutions for every travel business", "প্রতিটি ট্রাভেল ব্যবসার জন্য সলিউশন"),
    T("Pick the setup that matches how you sell. Every solution runs on the same platform, so you can add more later.",
      "আপনি যেভাবে বিক্রি করেন, সেই অনুযায়ী সেটআপ বেছে নিন। প্রতিটি সলিউশন একই প্ল্যাটফর্মে চলে, তাই পরে আরও যোগ করতে পারবেন।"),
    T("Explore solution", "সলিউশন দেখুন"),
    T("Common challenges", "সাধারণ সমস্যা"),
    T("What slows these businesses down", "যা এই ব্যবসাগুলোকে পিছিয়ে দেয়"),
    T("How TravelSuite helps", "TravelSuite যেভাবে সাহায্য করে"),
    T("Built around your daily work", "আপনার প্রতিদিনের কাজকে ঘিরে তৈরি"),
    T("Recommended modules", "প্রস্তাবিত মডিউল"),
    T("Recommended plan", "প্রস্তাবিত প্ল্যান"),
    T("See plan details", "প্ল্যানের বিস্তারিত দেখুন"),
    T("Other solutions", "অন্যান্য সলিউশন"),
    T("Blog", "ব্লগ"),
    T("TravelSuite blog", "TravelSuite ব্লগ"),
    T("Guides, ideas and news for travel agencies running their business online.",
      "অনলাইনে ব্যবসা চালানো ট্রাভেল এজেন্সির জন্য গাইড, আইডিয়া ও খবর।"),
    T("Latest from the blog", "ব্লগের সর্বশেষ লেখা"),
    T("Practical guides for travel agencies", "ট্রাভেল এজেন্সির জন্য কাজের গাইড"),
    T("Read article", "লেখাটি পড়ুন"),
    T("View all articles", "সব লেখা দেখুন"),
    T("All", "সব"),
    T("Filter articles by category", "বিভাগ অনুযায়ী লেখা দেখুন"),
    T("min read", "মিনিটে পড়া"),
    T("Back to blog", "ব্লগে ফিরুন"),
    T("Share this article", "লেখাটি শেয়ার করুন"),
    T("Related articles", "সম্পর্কিত লেখা"),
    T("TravelSuite Team", "TravelSuite টিম"),
    T("Want to see this in your agency?", "আপনার এজেন্সিতে এটা দেখতে চান?"),
    T("Book a free 30-minute walkthrough with our team.", "আমাদের টিমের সাথে ৩০ মিনিটের ফ্রি ওয়াকথ্রু বুক করুন।"),
    T("Legal", "আইনি তথ্য"),
    T("Last updated: 9 October 2026", "সর্বশেষ হালনাগাদ: ৯ অক্টোবর ২০২৬"),
    T("On this page", "এই পেজে"),
    T("Questions about this policy?", "এই নীতি নিয়ে প্রশ্ন আছে?"),
    T("Message us on WhatsApp at +880 13 2527 7120 and our team will help.",
      "+880 13 2527 7120 নম্বরে WhatsApp-এ মেসেজ দিন, আমাদের টিম সাহায্য করবে।"),
    T("Terms & Conditions", "শর্তাবলি"),
    T("Privacy Policy", "গোপনীয়তা নীতি"),
    T("Refund Policy", "রিফান্ড নীতি"),
    T("All solutions", "সব সলিউশন"),
    T("Breadcrumb", "পেজের অবস্থান"),
]

# ---------------------------------------------------------------------------
# Features (6 travel services, 9 business modules, 4 platform parts)
# ---------------------------------------------------------------------------
FEATURE_GROUPS = [
    ("services", "Travel services"),
    ("modules", "Business modules"),
    ("platform", "Platform"),
]

FEATURES = [
    # ---- Travel services
    dict(slug="flights", group="services", icon="i-plane", title="Flight Tickets",
         desc="Search, book and ticket flights for walk-in customers, online travellers and B2B agents.",
         intro=T("Sell air tickets to walk-in customers, online travellers and your agent network from one screen. Every ticket you issue updates the customer's file, the agent's balance and your accounts at the same time.",
                 "সরাসরি আসা কাস্টমার, অনলাইন যাত্রী ও আপনার এজেন্ট নেটওয়ার্কের কাছে এক স্ক্রিন থেকে এয়ার টিকিট বিক্রি করুন। প্রতিটি টিকিট ইস্যুর সাথে সাথে কাস্টমারের ফাইল, এজেন্টের ব্যালান্স ও আপনার হিসাব একসাথে আপডেট হয়।"),
         bullets=["Fare search with filters for airline, stops and baggage", "PNR creation, ticket issue, reissue, void and refund",
                  "Fare rules, baggage and seat information", "Agent-wise markup, commission and service fee",
                  "Group bookings and name changes", "E-ticket and invoice sent automatically"],
         steps=[T("Search fares from your connected suppliers", "সংযুক্ত সাপ্লায়ার থেকে ভাড়া খুঁজুন"),
                T("Create the PNR and collect payment", "PNR তৈরি করে পেমেন্ট নিন"),
                T("Issue the ticket; invoice and ledger update automatically", "টিকিট ইস্যু করুন; ইনভয়েস ও লেজার অটোমেটিক আপডেট হয়")],
         benefits=[T("No manual entry between GDS and accounts", "GDS আর হিসাবের মধ্যে হাতে এন্ট্রি নেই"),
                   T("Correct markup for every agent and channel", "প্রতিটি এজেন্ট ও চ্যানেলে সঠিক মার্কআপ"),
                   T("Refunds and reissues tracked to the last taka", "রিফান্ড ও রিইস্যুর হিসাব শেষ টাকা পর্যন্ত")]),
    dict(slug="hotels", group="services", icon="i-bed", title="Hotel Booking",
         desc="Sell your contracted hotels next to supplier inventory with clear room-level pricing.",
         intro=T("Load your own hotel contracts and sell them next to live supplier rates. Room types, allotments, meal plans and cancellation rules are all handled in one place.",
                 "নিজের হোটেল চুক্তি যোগ করে লাইভ সাপ্লায়ার রেটের পাশাপাশি বিক্রি করুন। রুমের ধরন, অ্যালটমেন্ট, খাবারের প্ল্যান ও বাতিলের নিয়ম — সব এক জায়গায়।"),
         bullets=["Hotel, room type and rate plan management", "Allotments, stop-sell and blackout dates",
                  "Child policy, meal plans and cancellation rules", "Supplier API and own contracts side by side",
                  "Room-level markup by market or agent", "Hotel vouchers with your branding"],
         steps=[T("Add hotels, rooms and contracted rates", "হোটেল, রুম ও চুক্তির রেট যোগ করুন"),
                T("Set allotments, markups and policies", "অ্যালটমেন্ট, মার্কআপ ও নীতি ঠিক করুন"),
                T("Sell online, to agents or at the counter", "অনলাইনে, এজেন্টদের কাছে বা কাউন্টারে বিক্রি করুন")],
         benefits=[T("Your own contracts earn better margins", "নিজের চুক্তিতে বেশি মুনাফা"),
                   T("No double-selling of allotted rooms", "বরাদ্দ রুম দুবার বিক্রি হয় না"),
                   T("Branded vouchers in seconds", "কয়েক সেকেন্ডে ব্র্যান্ডেড ভাউচার")]),
    dict(slug="hajj", group="services", icon="i-kaaba", title="Hajj & Umrah",
         desc="Run pilgrim operations from registration to return, with packages and payments in one place.",
         intro=T("Built for Hajj and Umrah agencies: register pilgrims, build packages, allocate groups and rooms, track visas and collect instalments without a single spreadsheet.",
                 "হজ ও উমরাহ এজেন্সির জন্য তৈরি: হাজি রেজিস্ট্রেশন, প্যাকেজ তৈরি, গ্রুপ ও রুম বণ্টন, ভিসা ট্র্যাকিং এবং কিস্তি আদায় — কোনো স্প্রেডশিট ছাড়াই।"),
         bullets=["Pilgrim registration with passport and photo", "Package builder: flights, Makkah & Madinah hotels, transport",
                  "Group and room allocation", "Visa and document status per pilgrim",
                  "Instalment payments and due reminders", "Mua'llim, guide and service provider records"],
         steps=[T("Register pilgrims with passport details", "পাসপোর্টের তথ্যসহ হাজি রেজিস্ট্রেশন করুন"),
                T("Assign packages, groups and rooms", "প্যাকেজ, গ্রুপ ও রুম বরাদ্দ করুন"),
                T("Track visas, payments and departures", "ভিসা, পেমেন্ট ও যাত্রা ট্র্যাক করুন")],
         benefits=[T("Every pilgrim's file complete before departure", "যাত্রার আগে প্রতিটি হাজির ফাইল সম্পূর্ণ"),
                   T("Instalments collected on time", "সময়মতো কিস্তি আদায়"),
                   T("Clear profit per package and group", "প্রতি প্যাকেজ ও গ্রুপে স্পষ্ট মুনাফা")]),
    dict(slug="visa", group="services", icon="i-passport", title="Visa Processing",
         desc="Organise every application with requirements, documents and stages your team can track.",
         intro=T("Turn visa processing into a clear pipeline. Each application has its checklist, documents, responsible staff and status, and customers are updated automatically.",
                 "ভিসা প্রসেসিংকে একটি পরিষ্কার ধাপে সাজান। প্রতিটি আবেদনের চেকলিস্ট, ডকুমেন্ট, দায়িত্বপ্রাপ্ত স্টাফ ও স্ট্যাটাস থাকে, আর কাস্টমার অটোমেটিক আপডেট পান।"),
         bullets=["Country and visa-type requirement lists", "Document upload and checklist per applicant",
                  "Application stages with responsible staff", "Embassy appointment and submission dates",
                  "Automatic SMS, email and WhatsApp status updates", "Visa fee, service charge and profit report"],
         steps=[T("Open a file with the right checklist", "সঠিক চেকলিস্টসহ ফাইল খুলুন"),
                T("Collect documents and submit", "ডকুমেন্ট সংগ্রহ করে জমা দিন"),
                T("Update the stage; the customer is notified", "ধাপ আপডেট করুন; কাস্টমার নোটিফিকেশন পান")],
         benefits=[T("No missing documents at submission", "জমার সময় কোনো ডকুমেন্ট বাদ পড়ে না"),
                   T("Fewer calls asking for status", "স্ট্যাটাস জানতে কম ফোন"),
                   T("Profit visible for every file", "প্রতিটি ফাইলের মুনাফা দেখা যায়")]),
    dict(slug="tours", group="services", icon="i-map", title="Tour Packages",
         desc="Design packages once and sell them on your website, to agents and over WhatsApp.",
         intro=T("Build attractive packages with day-by-day itineraries, departures and pricing, then sell the same package on your website, to agents and through WhatsApp.",
                 "দিনভিত্তিক ভ্রমণসূচি, ডিপারচার ও মূল্যসহ আকর্ষণীয় প্যাকেজ তৈরি করুন, তারপর একই প্যাকেজ ওয়েবসাইটে, এজেন্টদের কাছে ও WhatsApp-এ বিক্রি করুন।"),
         bullets=["Day-by-day itinerary builder with photos", "Fixed departures and seat inventory",
                  "Adult, child and group pricing", "Inclusions, exclusions and terms",
                  "Shareable PDF brochures", "Supplier costing and package profit"],
         steps=[T("Build the itinerary and costing", "ভ্রমণসূচি ও খরচ তৈরি করুন"),
                T("Publish departures and prices", "ডিপারচার ও মূল্য প্রকাশ করুন"),
                T("Take bookings from every channel", "সব চ্যানেল থেকে বুকিং নিন")],
         benefits=[T("One package, sold everywhere", "একটি প্যাকেজ, সব জায়গায় বিক্রি"),
                   T("Seats never oversold", "সিট কখনো বেশি বিক্রি হয় না"),
                   T("Know your margin before you sell", "বিক্রির আগেই মুনাফা জানুন")]),
    dict(slug="transport", group="services", icon="i-car", title="Transport Booking",
         desc="Handle airport transfers, intercity transport and rentals with vehicles and drivers.",
         intro=T("Manage your own vehicles and hired transport for transfers, tours and rentals, with drivers, routes and pricing linked to every booking.",
                 "ট্রান্সফার, ট্যুর ও ভাড়ার জন্য নিজের গাড়ি ও ভাড়া করা ট্রান্সপোর্ট পরিচালনা করুন, ড্রাইভার, রুট ও মূল্য প্রতিটি বুকিংয়ের সাথে যুক্ত।"),
         bullets=["Vehicle and driver management", "Zone and route-based pricing",
                  "Airport pick-up and drop scheduling", "Driver assignment and trip sheets",
                  "Add transport to any package or booking", "Vendor payables for hired vehicles"],
         steps=[T("Add vehicles, drivers and routes", "গাড়ি, ড্রাইভার ও রুট যোগ করুন"),
                T("Attach transport to a booking", "বুকিংয়ের সাথে ট্রান্সপোর্ট যুক্ত করুন"),
                T("Send the trip sheet to the driver", "ড্রাইভারকে ট্রিপ শিট পাঠান")],
         benefits=[T("No missed airport pick-ups", "কোনো এয়ারপোর্ট পিক-আপ মিস হয় না"),
                   T("Vendor bills match actual trips", "ভেন্ডরের বিল আসল ট্রিপের সাথে মেলে"),
                   T("Transport adds margin to every package", "প্রতিটি প্যাকেজে ট্রান্সপোর্ট থেকে বাড়তি মুনাফা")]),
    # ---- Business modules
    dict(slug="crm", group="modules", icon="i-users", title="CRM",
         desc="Every customer, lead and conversation in one profile.",
         intro=T("Keep every customer's history, documents and conversations in one profile, and move each inquiry through a clear pipeline until it becomes a booking.",
                 "প্রতিটি কাস্টমারের ইতিহাস, ডকুমেন্ট ও কথোপকথন এক প্রোফাইলে রাখুন, আর প্রতিটি ইনকোয়ারিকে পরিষ্কার ধাপে বুকিং পর্যন্ত নিয়ে যান।"),
         bullets=["Customer profiles with travel history and documents", "Lead pipeline from inquiry to booking",
                  "Follow-up reminders and activity log", "Lead source tracking: website, WhatsApp, Facebook, walk-in",
                  "Customer segments for offers", "Birthday and passport-expiry reminders"],
         steps=[T("Capture leads from every channel", "সব চ্যানেল থেকে লিড সংগ্রহ করুন"),
                T("Follow up with reminders and templates", "রিমাইন্ডার ও টেমপ্লেট দিয়ে ফলো-আপ করুন"),
                T("Convert to a booking in one click", "এক ক্লিকে বুকিংয়ে রূপান্তর করুন")],
         benefits=[T("No inquiry forgotten", "কোনো ইনকোয়ারি ভুলে যাওয়া হয় না"),
                   T("Repeat customers recognised instantly", "পুরনো কাস্টমার সাথে সাথে চেনা যায়"),
                   T("Know which channel brings sales", "কোন চ্যানেল থেকে বিক্রি আসে জানুন")]),
    dict(slug="sales", group="modules", icon="i-trend", title="Sales Management",
         desc="Turn inquiries into confirmed bookings and see how your team performs.",
         intro=T("Send professional quotations, follow them to confirmation and see exactly how each salesperson and branch is performing against target.",
                 "পেশাদার কোটেশন পাঠান, কনফার্মেশন পর্যন্ত ফলো করুন এবং প্রতিটি সেলসপারসন ও শাখা টার্গেটের তুলনায় কেমন করছে দেখুন।"),
         bullets=["Quotations with multiple options", "Convert a quote to a booking in one click",
                  "Sales targets by staff and branch", "Conversion and win-rate reports",
                  "Discount approval rules", "Commission for sales staff"],
         steps=[T("Send a quotation with options", "অপশনসহ কোটেশন পাঠান"),
                T("Track it until the customer decides", "কাস্টমার সিদ্ধান্ত নেওয়া পর্যন্ত ট্র্যাক করুন"),
                T("Confirm and pay commission automatically", "কনফার্ম করুন, কমিশন অটোমেটিক হিসাব হয়")],
         benefits=[T("Faster, consistent quotations", "দ্রুত ও একই মানের কোটেশন"),
                   T("Targets everyone can see", "সবাই দেখতে পায় এমন টার্গেট"),
                   T("Discounts under control", "ডিসকাউন্ট নিয়ন্ত্রণে")]),
    dict(slug="finance", group="modules", icon="i-wallet", title="Finance & Accounting",
         desc="Double-entry accounting that updates itself with every booking and payment.",
         intro=T("A full double-entry accounting system made for travel. Bookings, payments, refunds and supplier bills post themselves, so your books are always up to date.",
                 "ট্রাভেলের জন্য তৈরি পূর্ণ ডাবল-এন্ট্রি অ্যাকাউন্টিং। বুকিং, পেমেন্ট, রিফান্ড ও সাপ্লায়ার বিল নিজে নিজে পোস্ট হয়, তাই হিসাব সবসময় হালনাগাদ থাকে।"),
         bullets=["Chart of accounts, journals and ledgers", "Customer, agent and supplier balances",
                  "Bank, cash, bKash and Nagad accounts", "Profit and loss, balance sheet and trial balance",
                  "Multi-currency with exchange gain or loss", "Branch and cost-centre accounting"],
         steps=[T("Bookings and payments post automatically", "বুকিং ও পেমেন্ট অটোমেটিক পোস্ট হয়"),
                T("Reconcile bank, bKash and Nagad", "ব্যাংক, বিকাশ ও নগদ মিলিয়ে নিন"),
                T("Close the month with ready reports", "তৈরি রিপোর্ট দিয়ে মাস শেষ করুন")],
         benefits=[T("Month-end closing in a day", "এক দিনে মাসিক হিসাব ক্লোজিং"),
                   T("Real profit, not estimates", "আনুমানিক নয়, আসল মুনাফা"),
                   T("Audit-ready records", "অডিটের জন্য প্রস্তুত রেকর্ড")]),
    dict(slug="hr", group="modules", icon="i-idcard", title="HR & Employees",
         desc="Manage your team, attendance and payroll in the same system.",
         intro=T("Manage staff records, attendance, leave and payroll alongside the work they do, with permissions that control what each person can see.",
                 "স্টাফের তথ্য, হাজিরা, ছুটি ও বেতন তাদের কাজের পাশেই পরিচালনা করুন, আর পারমিশন দিয়ে ঠিক করুন কে কী দেখবে।"),
         bullets=["Employee profiles and documents", "Attendance and leave management",
                  "Payroll with allowances and deductions", "Roles and permissions per staff member",
                  "Staff targets and incentives", "Branch and department structure"],
         steps=[T("Add employees, roles and branches", "কর্মী, রোল ও শাখা যোগ করুন"),
                T("Record attendance and leave", "হাজিরা ও ছুটি রেকর্ড করুন"),
                T("Run payroll with incentives included", "ইনসেনটিভসহ বেতন তৈরি করুন")],
         benefits=[T("Payroll in minutes", "মিনিটেই বেতনের হিসাব"),
                   T("Right access for every role", "প্রতিটি রোলের জন্য সঠিক অ্যাক্সেস"),
                   T("Incentives linked to real sales", "আসল বিক্রির সাথে যুক্ত ইনসেনটিভ")]),
    dict(slug="helpdesk", group="modules", icon="i-headset", title="Help Desk & Support",
         desc="Resolve customer issues quickly and keep a full history.",
         intro=T("Handle complaints, changes and questions as tickets linked to the customer's bookings, so nothing is lost between staff or shifts.",
                 "অভিযোগ, পরিবর্তন ও প্রশ্নগুলো কাস্টমারের বুকিংয়ের সাথে যুক্ত টিকিট হিসেবে পরিচালনা করুন, যাতে স্টাফ বা শিফট বদলালেও কিছু হারিয়ে না যায়।"),
         bullets=["Support tickets from any channel", "Assignment to staff or teams",
                  "Priority and SLA tracking", "Linked to the customer's bookings",
                  "Internal notes and attachments", "Satisfaction feedback"],
         steps=[T("A ticket opens from any channel", "যেকোনো চ্যানেল থেকে টিকিট খোলে"),
                T("Assign it with a priority", "অগ্রাধিকারসহ দায়িত্ব দিন"),
                T("Resolve it and collect feedback", "সমাধান করে মতামত নিন")],
         benefits=[T("Faster resolution times", "দ্রুত সমাধান"),
                   T("Full history for every customer", "প্রতিটি কাস্টমারের পূর্ণ ইতিহাস"),
                   T("Service quality you can measure", "মাপা যায় এমন সার্ভিস মান")]),
    dict(slug="expenses", group="modules", icon="i-receipt", title="Expense Management",
         desc="Track every taka spent, by branch, trip or category.",
         intro=T("Record office and trip expenses with receipts and approvals, and see exactly where money goes by branch, trip or category.",
                 "রসিদ ও অনুমোদনসহ অফিস ও ট্রিপের খরচ রেকর্ড করুন, আর শাখা, ট্রিপ বা খাত অনুযায়ী টাকা কোথায় যাচ্ছে দেখুন।"),
         bullets=["Expense categories and budgets", "Receipt upload", "Approval workflow",
                  "Trip and group expenses", "Branch-wise cost reports", "Posted to accounts automatically"],
         steps=[T("Staff submit expenses with receipts", "স্টাফ রসিদসহ খরচ জমা দেন"),
                T("Managers approve or reject", "ম্যানেজার অনুমোদন বা বাতিল করেন"),
                T("Approved expenses post to accounts", "অনুমোদিত খরচ হিসাবে পোস্ট হয়")],
         benefits=[T("Spending within budget", "বাজেটের মধ্যে খরচ"),
                   T("No lost receipts", "কোনো রসিদ হারায় না"),
                   T("True cost of every trip", "প্রতিটি ট্রিপের আসল খরচ")]),
    dict(slug="invoices", group="modules", icon="i-file", title="Invoice & Payment",
         desc="Bill customers and agents correctly and follow up on dues.",
         intro=T("Create branded invoices and receipts, accept partial and online payments, and follow up on every due amount automatically.",
                 "ব্র্যান্ডেড ইনভয়েস ও রসিদ তৈরি করুন, আংশিক ও অনলাইন পেমেন্ট নিন, আর প্রতিটি বকেয়া অটোমেটিক ফলো-আপ করুন।"),
         bullets=["Branded invoices and money receipts", "Partial and instalment payments", "Online payment links",
                  "Due and overdue reminders", "Refunds and credit notes", "Agent wallet and deposit top-ups"],
         steps=[T("Invoice is created with the booking", "বুকিংয়ের সাথে ইনভয়েস তৈরি হয়"),
                T("Share a payment link or take cash", "পেমেন্ট লিংক পাঠান বা ক্যাশ নিন"),
                T("Reminders go out until it is paid", "পরিশোধ না হওয়া পর্যন্ত রিমাইন্ডার যায়")],
         benefits=[T("Paid faster", "দ্রুত পেমেন্ট"),
                   T("Fewer billing mistakes", "বিলিংয়ে কম ভুল"),
                   T("Dues visible at a glance", "এক নজরে বকেয়া")]),
    dict(slug="reports", group="modules", icon="i-chart", title="Reports & Analytics",
         desc="See what's selling, what's profitable and what's owed.",
         intro=T("Ready-made reports show sales, profit, receivables and performance across services, staff, branches and agents, all exportable to Excel and PDF.",
                 "তৈরি রিপোর্টে সার্ভিস, স্টাফ, শাখা ও এজেন্ট অনুযায়ী সেলস, মুনাফা, প্রাপ্য ও পারফরম্যান্স দেখা যায়, সব Excel ও PDF-এ এক্সপোর্টযোগ্য।"),
         bullets=["Sales by service, staff, branch and agent", "Profit per booking and per package",
                  "Receivable and payable aging", "Cash flow and daily cash book",
                  "Airline and supplier performance", "Export to Excel and PDF"],
         steps=[T("Data flows in from every module", "প্রতিটি মডিউল থেকে ডেটা আসে"),
                T("Filter by date, branch or service", "তারিখ, শাখা বা সার্ভিস অনুযায়ী ফিল্টার করুন"),
                T("Export or share with partners", "এক্সপোর্ট করুন বা পার্টনারদের সাথে শেয়ার করুন")],
         benefits=[T("Decisions based on real numbers", "আসল সংখ্যার ভিত্তিতে সিদ্ধান্ত"),
                   T("Spot unprofitable services early", "লোকসানি সার্ভিস আগেই ধরা পড়ে"),
                   T("Collect dues before they age", "বকেয়া পুরনো হওয়ার আগেই আদায়")]),
    dict(slug="tasks", group="modules", icon="i-tasks", title="Tasks & Workflows",
         desc="Assign work, set deadlines and automate routine handovers.",
         intro=T("Assign work linked to bookings and customers, set deadlines, and let routine handovers happen automatically when a booking changes.",
                 "বুকিং ও কাস্টমারের সাথে যুক্ত কাজ ভাগ করুন, ডেডলাইন দিন, আর বুকিং বদলালে নিয়মিত হস্তান্তর নিজে নিজে হতে দিন।"),
         bullets=["Tasks linked to bookings and customers", "Due dates and reminders", "Team task boards",
                  "Automatic tasks on booking events", "Checklists for visa and Hajj files", "Activity timeline per file"],
         steps=[T("Create tasks or let bookings create them", "টাস্ক তৈরি করুন বা বুকিং থেকে তৈরি হোক"),
                T("Track progress on the team board", "টিম বোর্ডে অগ্রগতি দেখুন"),
                T("Get reminded before deadlines", "ডেডলাইনের আগে রিমাইন্ডার পান")],
         benefits=[T("Nothing falls through the cracks", "কোনো কাজ বাদ পড়ে না"),
                   T("Clear ownership of every file", "প্রতিটি ফাইলের স্পষ্ট দায়িত্ব"),
                   T("Less time chasing colleagues", "সহকর্মীদের পেছনে কম সময়")]),
    # ---- Platform
    dict(slug="b2b", group="platform", icon="i-layers", title="B2B & B2C Booking",
         desc="One inventory sold through a customer website and an agent portal.",
         intro=T("Sell the same inventory to travellers on your website and to registered agents through a B2B portal with net fares, credit limits and wallets.",
                 "একই ইনভেন্টরি আপনার ওয়েবসাইটে যাত্রীদের কাছে এবং নেট ভাড়া, ক্রেডিট লিমিট ও ওয়ালেটসহ B2B পোর্টালে নিবন্ধিত এজেন্টদের কাছে বিক্রি করুন।"),
         bullets=["B2B agent portal with net fares", "Agent registration and approval", "Credit limits, deposits and wallet",
                  "Sub-agent hierarchy and markups", "B2C customer accounts and booking history", "Online payment integration"],
         steps=[T("Agents register and you approve them", "এজেন্ট রেজিস্টার করেন, আপনি অনুমোদন দেন"),
                T("Set markups, credit and deposits", "মার্কআপ, ক্রেডিট ও ডিপোজিট ঠিক করুন"),
                T("Agents and customers book 24/7", "এজেন্ট ও কাস্টমার ২৪/৭ বুক করেন")],
         benefits=[T("Grow sales without more staff", "বাড়তি স্টাফ ছাড়াই বিক্রি বাড়ান"),
                   T("Credit risk under control", "ক্রেডিট ঝুঁকি নিয়ন্ত্রণে"),
                   T("Bookings even after office hours", "অফিস সময়ের পরেও বুকিং")]),
    dict(slug="website", group="platform", icon="i-globe", title="Agency Website",
         desc="A modern, fast website connected directly to your ERP.",
         intro=T("A fast, modern website on your own domain that shows your products, takes bookings and inquiries, and sends every lead straight into your CRM.",
                 "নিজের ডোমেইনে দ্রুত ও আধুনিক ওয়েবসাইট, যা আপনার প্রোডাক্ট দেখায়, বুকিং ও ইনকোয়ারি নেয় এবং প্রতিটি লিড সরাসরি CRM-এ পাঠায়।"),
         bullets=["Responsive design on your domain", "Travel product showcase", "Online booking and inquiry forms",
                  "CMS for pages, offers and blog", "SEO-friendly structure and meta tags", "Lead capture straight into CRM"],
         steps=[T("Choose a design and add your branding", "ডিজাইন বেছে নিয়ে ব্র্যান্ডিং যোগ করুন"),
                T("Publish products, offers and pages", "প্রোডাক্ট, অফার ও পেজ প্রকাশ করুন"),
                T("Receive bookings and leads in the ERP", "ERP-তে বুকিং ও লিড পান")],
         benefits=[T("Look as professional as the big OTAs", "বড় OTA-র মতো পেশাদার চেহারা"),
                   T("Found on Google", "Google-এ খুঁজে পাওয়া যায়"),
                   T("Every visitor can become a lead", "প্রতিটি ভিজিটর হতে পারে লিড")]),
    dict(slug="ai", group="platform", icon="i-bot", title="AI Automation",
         desc="AI that answers, qualifies and follows up while your team sleeps.",
         intro=T("AI agents answer common questions, draft itineraries, qualify leads and follow up automatically, so your team spends time on the customers ready to book.",
                 "AI এজেন্ট সাধারণ প্রশ্নের উত্তর দেয়, ভ্রমণসূচির খসড়া তৈরি করে, লিড যাচাই করে এবং অটোমেটিক ফলো-আপ করে, তাই আপনার টিম বুক করতে প্রস্তুত কাস্টমারদের দিকে মন দিতে পারে।"),
         bullets=["AI agents for customer queries", "AI trip planner for itineraries", "Lead qualification and scoring",
                  "Automated follow-ups", "Task and workflow automation", "AI-assisted reports and summaries"],
         steps=[T("Connect your channels and products", "চ্যানেল ও প্রোডাক্ট যুক্ত করুন"),
                T("AI answers and qualifies inquiries", "AI ইনকোয়ারির উত্তর দেয় ও যাচাই করে"),
                T("Your team takes over warm leads", "আগ্রহী লিড আপনার টিম নেয়")],
         benefits=[T("Instant replies, day and night", "দিন-রাত সাথে সাথে উত্তর"),
                   T("Staff focus on ready buyers", "স্টাফ প্রস্তুত ক্রেতাদের দিকে মন দেয়"),
                   T("Itinerary drafts in seconds", "সেকেন্ডে ভ্রমণসূচির খসড়া")]),
    dict(slug="omnichannel", group="platform", icon="i-chat", title="Omnichannel Inbox",
         desc="Every customer conversation in one shared inbox.",
         intro=T("Bring WhatsApp, Messenger and Instagram messages into one shared inbox, assign them to your team and turn any chat into a CRM lead.",
                 "WhatsApp, Messenger ও Instagram-এর মেসেজ একটি শেয়ার্ড ইনবক্সে আনুন, টিমকে দায়িত্ব দিন এবং যেকোনো চ্যাটকে CRM লিডে রূপান্তর করুন।"),
         bullets=["WhatsApp, Messenger and Instagram", "Team-based assignment", "Saved replies and templates",
                  "Full conversation history", "Turn a chat into a CRM lead", "Linked to bookings and payments"],
         steps=[T("Connect your business accounts", "বিজনেস অ্যাকাউন্টগুলো যুক্ত করুন"),
                T("Messages arrive in one inbox", "সব মেসেজ এক ইনবক্সে আসে"),
                T("Assign, reply and convert to leads", "দায়িত্ব দিন, উত্তর দিন, লিডে রূপান্তর করুন")],
         benefits=[T("No message missed across channels", "কোনো চ্যানেলের মেসেজ মিস হয় না"),
                   T("Shared phones no longer needed", "শেয়ার করা ফোনের আর দরকার নেই"),
                   T("Every chat linked to the customer", "প্রতিটি চ্যাট কাস্টমারের সাথে যুক্ত")]),
]

# ---------------------------------------------------------------------------
# Solutions
# ---------------------------------------------------------------------------
SOLUTIONS = [
    dict(slug="travel-agencies", icon="i-building", title="Travel agencies", tagline="Ticketing, hotels and visa under one roof",
         headline=T("One system for the counter, the phone and the website", "কাউন্টার, ফোন ও ওয়েবসাইটের জন্য একটি সিস্টেম"),
         intro=T("Most agencies sell tickets, hotels, visas and tours to the same customers. TravelSuite ERP puts all of it on one screen, with the accounts updating as you work.",
                 "বেশিরভাগ এজেন্সি একই কাস্টমারের কাছে টিকিট, হোটেল, ভিসা ও ট্যুর বিক্রি করে। TravelSuite ERP সবকিছু এক স্ক্রিনে আনে, আর কাজের সাথে সাথে হিসাব আপডেট হয়।"),
         challenges=[T("Customer details re-typed for every service", "প্রতিটি সার্ভিসের জন্য কাস্টমারের তথ্য বারবার লেখা"),
                     T("Ticket sales and accounts never quite match", "টিকিট বিক্রি আর হিসাব কখনো পুরো মেলে না"),
                     T("Inquiries lost across phones and WhatsApp", "ফোন আর WhatsApp-এ ইনকোয়ারি হারিয়ে যায়")],
         helps=[T("One customer profile for every service", "সব সার্ভিসের জন্য একটি কাস্টমার প্রোফাইল"),
                T("Tickets and invoices post straight to the ledger", "টিকিট ও ইনভয়েস সরাসরি লেজারে পোস্ট হয়"),
                T("A shared inbox for every inquiry", "প্রতিটি ইনকোয়ারির জন্য শেয়ার্ড ইনবক্স"),
                T("Daily sales and profit at a glance", "এক নজরে দৈনিক বিক্রি ও মুনাফা")],
         modules=["flights", "hotels", "visa", "crm", "finance", "omnichannel"], plan="Growth"),
    dict(slug="hajj-umrah", icon="i-kaaba", title="Hajj & Umrah operators", tagline="Pilgrim registration, groups, packages",
         headline=T("Every pilgrim, package and payment in one place", "প্রতিটি হাজি, প্যাকেজ ও পেমেন্ট এক জায়গায়"),
         intro=T("Hajj and Umrah seasons bring hundreds of pilgrims, each with documents, visas, rooms and instalments. TravelSuite ERP keeps every file complete and every payment on time.",
                 "হজ ও উমরাহ মৌসুমে শত শত হাজি আসেন, প্রত্যেকের ডকুমেন্ট, ভিসা, রুম ও কিস্তি থাকে। TravelSuite ERP প্রতিটি ফাইল সম্পূর্ণ ও প্রতিটি পেমেন্ট সময়মতো রাখে।"),
         challenges=[T("Pilgrim lists kept in spreadsheets", "হাজির তালিকা স্প্রেডশিটে রাখা"),
                     T("Instalments and dues hard to follow up", "কিস্তি ও বকেয়া ফলো-আপ করা কঠিন"),
                     T("Room and group allocation done by hand", "রুম ও গ্রুপ বণ্টন হাতে করা")],
         helps=[T("Pilgrim registration with passport and photo", "পাসপোর্ট ও ছবিসহ হাজি রেজিস্ট্রেশন"),
                T("Package builder: flights, Makkah & Madinah hotels, transport", "প্যাকেজ বিল্ডার: ফ্লাইট, মক্কা ও মদিনার হোটেল, ট্রান্সপোর্ট"),
                T("Instalment payments and due reminders", "কিস্তিতে পেমেন্ট ও বকেয়ার রিমাইন্ডার"),
                T("Group and room allocation", "গ্রুপ ও রুম বণ্টন")],
         modules=["hajj", "visa", "transport", "invoices", "finance", "omnichannel"], plan="Business"),
    dict(slug="b2b-consolidators", icon="i-users", title="B2B consolidators", tagline="Agent network, credit and commissions",
         headline=T("Grow your agent network without growing your back office", "ব্যাক অফিস না বাড়িয়েই এজেন্ট নেটওয়ার্ক বাড়ান"),
         intro=T("Consolidators live on volume and credit control. TravelSuite ERP gives every agent a self-service portal while you keep markups, credit limits and balances under control.",
                 "কনসোলিডেটরের ব্যবসা চলে বিক্রির পরিমাণ ও ক্রেডিট নিয়ন্ত্রণে। TravelSuite ERP প্রতিটি এজেন্টকে নিজে বুক করার পোর্টাল দেয়, আর মার্কআপ, ক্রেডিট লিমিট ও ব্যালান্স থাকে আপনার নিয়ন্ত্রণে।"),
         challenges=[T("Agents call or message for every booking", "প্রতিটি বুকিংয়ের জন্য এজেন্টরা ফোন বা মেসেজ করেন"),
                     T("Credit given without clear limits", "স্পষ্ট লিমিট ছাড়াই ক্রেডিট দেওয়া"),
                     T("Agent statements prepared manually", "এজেন্ট স্টেটমেন্ট হাতে তৈরি করা")],
         helps=[T("B2B agent portal with net fares", "নেট ভাড়াসহ B2B এজেন্ট পোর্টাল"),
                T("Credit limits, deposits and wallet", "ক্রেডিট লিমিট, ডিপোজিট ও ওয়ালেট"),
                T("Sub-agent hierarchy and markups", "সাব-এজেন্ট কাঠামো ও মার্কআপ"),
                T("Agent ledgers and statements on demand", "চাহিবামাত্র এজেন্ট লেজার ও স্টেটমেন্ট")],
         modules=["b2b", "flights", "finance", "invoices", "reports", "sales"], plan="Business"),
    dict(slug="tour-operators", icon="i-map", title="Tour operators & DMCs", tagline="Packages, departures, suppliers",
         headline=T("Design packages once, sell them everywhere", "একবার প্যাকেজ তৈরি করুন, সব জায়গায় বিক্রি করুন"),
         intro=T("Tour operators juggle itineraries, departures, suppliers and costing. TravelSuite ERP connects them, so every package shows its real margin before you sell a seat.",
                 "ট্যুর অপারেটরদের ভ্রমণসূচি, ডিপারচার, সাপ্লায়ার ও খরচ একসাথে সামলাতে হয়। TravelSuite ERP এগুলো যুক্ত করে, তাই একটি সিট বিক্রির আগেই প্রতিটি প্যাকেজের আসল মুনাফা দেখা যায়।"),
         challenges=[T("Itineraries rebuilt in Word for every customer", "প্রতিটি কাস্টমারের জন্য Word-এ নতুন করে ভ্রমণসূচি"),
                     T("Seats oversold on popular departures", "জনপ্রিয় ডিপারচারে সিট বেশি বিক্রি"),
                     T("Supplier costs unclear until the trip ends", "ট্রিপ শেষ না হওয়া পর্যন্ত সাপ্লায়ার খরচ অস্পষ্ট")],
         helps=[T("Day-by-day itinerary builder with photos", "ছবিসহ দিনভিত্তিক ভ্রমণসূচি তৈরি"),
                T("Fixed departures and seat inventory", "নির্দিষ্ট ডিপারচার ও সিট ইনভেন্টরি"),
                T("Supplier costing and package profit", "সাপ্লায়ার খরচ ও প্যাকেজ মুনাফা"),
                T("Shareable PDF brochures", "শেয়ারযোগ্য PDF ব্রোশিওর")],
         modules=["tours", "transport", "hotels", "website", "expenses", "ai"], plan="Growth"),
    dict(slug="online-travel-agencies", icon="i-globe", title="Online travel agencies", tagline="B2C website with online payment",
         headline=T("Your own OTA, on your own domain", "নিজের ডোমেইনে নিজের OTA"),
         intro=T("Launch a booking website that looks and works like the big OTAs, with online payment, customer accounts and AI that answers questions around the clock.",
                 "বড় OTA-র মতো দেখতে ও চলে এমন বুকিং ওয়েবসাইট চালু করুন, অনলাইন পেমেন্ট, কাস্টমার অ্যাকাউন্ট আর সারাক্ষণ প্রশ্নের উত্তর দেওয়া AI-সহ।"),
         challenges=[T("Website and back office not connected", "ওয়েবসাইট আর ব্যাক অফিস যুক্ত নয়"),
                     T("Visitors leave without booking", "ভিজিটর বুক না করেই চলে যায়"),
                     T("Questions arrive after office hours", "অফিস সময়ের পরে প্রশ্ন আসে")],
         helps=[T("Responsive design on your domain", "আপনার ডোমেইনে রেসপন্সিভ ডিজাইন"),
                T("Online booking integration", "অনলাইন বুকিং ইন্টিগ্রেশন"),
                T("AI agents for customer queries", "কাস্টমারের প্রশ্নের জন্য AI এজেন্ট"),
                T("Lead capture straight into CRM", "সরাসরি CRM-এ লিড সংগ্রহ")],
         modules=["website", "b2b", "flights", "hotels", "ai", "crm"], plan="Business"),
    dict(slug="corporate-travel", icon="i-idcard", title="Corporate travel desks", tagline="Policies, approvals, monthly billing",
         headline=T("Business travel with policies, approvals and one monthly bill", "পলিসি, অনুমোদন ও একটি মাসিক বিলসহ বিজনেস ট্রাভেল"),
         intro=T("Serve companies that need travel booked to policy, approved by managers and billed once a month, with every trip visible in reports.",
                 "যেসব কোম্পানির পলিসি মেনে ভ্রমণ বুকিং, ম্যানেজারের অনুমোদন ও মাসে একবার বিল দরকার, তাদের সেবা দিন, প্রতিটি ট্রিপ রিপোর্টে দেখা যায়।"),
         challenges=[T("Approvals chased over email", "ইমেইলে অনুমোদনের পেছনে ছোটা"),
                     T("Monthly invoices compiled by hand", "মাসিক ইনভয়েস হাতে তৈরি"),
                     T("Clients ask for spend reports", "ক্লায়েন্টরা খরচের রিপোর্ট চায়")],
         helps=[T("Approval workflow", "অনুমোদনের ধাপ"),
                T("Company accounts with monthly billing", "মাসিক বিলিংসহ কোম্পানি অ্যাকাউন্ট"),
                T("Sales by service, staff, branch and agent", "সার্ভিস, স্টাফ, শাখা ও এজেন্টভিত্তিক সেলস"),
                T("Export to Excel and PDF", "Excel ও PDF-এ এক্সপোর্ট")],
         modules=["flights", "hotels", "invoices", "reports", "tasks", "expenses"], plan="Growth"),
]

# ---------------------------------------------------------------------------
# Blog
# ---------------------------------------------------------------------------
BLOG_CATEGORIES = [T("Hajj & Umrah", "হজ ও উমরাহ"), T("B2B", "B2B"), T("Finance", "ফাইন্যান্স"),
                   T("Omnichannel", "অমনিচ্যানেল"), T("AI", "AI"), T("Guides", "গাইড")]

POSTS = [
    dict(slug="digitize-hajj-umrah-agency", cat="Hajj & Umrah", icon="i-kaaba", color="#184332",
         date=T("2 October 2026", "২ অক্টোবর ২০২৬"), read=6,
         title=T("How to digitize your Hajj & Umrah agency before the next season", "পরবর্তী মৌসুমের আগে কীভাবে আপনার হজ ও উমরাহ এজেন্সি ডিজিটাল করবেন"),
         excerpt=T("A practical plan to move pilgrim registration, packages and instalments out of spreadsheets.", "হাজি রেজিস্ট্রেশন, প্যাকেজ ও কিস্তির হিসাব স্প্রেডশিট থেকে সরিয়ে আনার একটি বাস্তব পরিকল্পনা।"),
         body=[
             ("p", T("Every season, Hajj and Umrah agencies handle hundreds of pilgrims with passports, visas, rooms, transport and instalment payments. When all of that lives in spreadsheets and notebooks, mistakes are expensive and stressful.",
                     "প্রতি মৌসুমে হজ ও উমরাহ এজেন্সিগুলো শত শত হাজির পাসপোর্ট, ভিসা, রুম, ট্রান্সপোর্ট ও কিস্তির পেমেন্ট সামলায়। এসব যখন স্প্রেডশিট আর খাতায় থাকে, তখন ভুলের মূল্য বেশি এবং চাপও বেশি।")),
             ("h2", T("Start with one pilgrim register", "একটি হাজি রেজিস্টার দিয়ে শুরু করুন")),
             ("p", T("Put every pilgrim in one register with passport details, photo, contact and emergency contact. This single list becomes the source for visas, rooms, flights and payments.",
                     "প্রতিটি হাজিকে পাসপোর্টের তথ্য, ছবি, যোগাযোগ ও জরুরি যোগাযোগসহ একটি রেজিস্টারে রাখুন। এই একটি তালিকাই হবে ভিসা, রুম, ফ্লাইট ও পেমেন্টের উৎস।")),
             ("h2", T("Build packages, not price lists", "মূল্যতালিকা নয়, প্যাকেজ তৈরি করুন")),
             ("p", T("Define each package with its flights, Makkah and Madinah hotels, transport and services. When a pilgrim joins a package, everything they need is attached automatically.",
                     "প্রতিটি প্যাকেজ ফ্লাইট, মক্কা ও মদিনার হোটেল, ট্রান্সপোর্ট ও সার্ভিসসহ ঠিক করুন। কোনো হাজি প্যাকেজে যুক্ত হলে তাঁর যা দরকার সব অটোমেটিক যুক্ত হয়ে যায়।")),
             ("h2", T("Make instalments visible", "কিস্তির হিসাব দৃশ্যমান করুন")),
             ("ul", [T("Record every instalment against the pilgrim's file", "প্রতিটি কিস্তি হাজির ফাইলে রেকর্ড করুন"),
                     T("Send due reminders by SMS and WhatsApp", "SMS ও WhatsApp-এ বকেয়ার রিমাইন্ডার পাঠান"),
                     T("See total collected and outstanding per group", "প্রতি গ্রুপে মোট আদায় ও বাকি দেখুন")]),
             ("p", T("With the register, packages and payments connected, your team can focus on serving pilgrims instead of reconciling lists.",
                     "রেজিস্টার, প্যাকেজ ও পেমেন্ট যুক্ত থাকলে আপনার টিম তালিকা মেলানোর বদলে হাজিদের সেবায় মন দিতে পারে।")),
         ]),
    dict(slug="b2b-agent-credit-limits", cat="B2B", icon="i-layers", color="#0e4a7a",
         date=T("24 September 2026", "২৪ সেপ্টেম্বর ২০২৬"), read=5,
         title=T("B2B travel portals: how agent credit limits protect your cash flow", "B2B ট্রাভেল পোর্টাল: এজেন্ট ক্রেডিট লিমিট কীভাবে আপনার ক্যাশ ফ্লো রক্ষা করে"),
         excerpt=T("Credit wins agents, but unmanaged credit sinks consolidators. Here is how to get the balance right.", "ক্রেডিট দিয়ে এজেন্ট পাওয়া যায়, কিন্তু অনিয়ন্ত্রিত ক্রেডিট কনসোলিডেটরকে ডুবিয়ে দেয়। কীভাবে ভারসাম্য রাখবেন জেনে নিন।"),
         body=[
             ("p", T("Sub-agents choose the consolidator who gives them credit. But every ticket issued on credit is cash you have already paid to the airline. Without limits, a few slow payers can freeze your business.",
                     "সাব-এজেন্টরা সেই কনসোলিডেটরকেই বেছে নেন যিনি ক্রেডিট দেন। কিন্তু ক্রেডিটে ইস্যু হওয়া প্রতিটি টিকিটের টাকা আপনি আগেই এয়ারলাইনকে দিয়ে দিয়েছেন। লিমিট না থাকলে কয়েকজন দেরিতে পরিশোধকারীই আপনার ব্যবসা আটকে দিতে পারেন।")),
             ("h2", T("Set limits per agent", "প্রতি এজেন্টের জন্য লিমিট ঠিক করুন")),
             ("p", T("Give each agent a credit limit based on their history and deposits. The portal blocks new bookings automatically when the limit is reached.",
                     "প্রতিটি এজেন্টকে তাঁর ইতিহাস ও ডিপোজিটের ভিত্তিতে ক্রেডিট লিমিট দিন। লিমিট পূর্ণ হলে পোর্টাল নিজে থেকেই নতুন বুকিং বন্ধ করে দেয়।")),
             ("h2", T("Encourage deposits with a wallet", "ওয়ালেট দিয়ে ডিপোজিটে উৎসাহ দিন")),
             ("p", T("A deposit wallet lets agents top up in advance by bank, bKash or Nagad and book instantly. You hold the cash before the ticket is issued.",
                     "ডিপোজিট ওয়ালেটে এজেন্টরা ব্যাংক, বিকাশ বা নগদে আগে থেকে টাকা রেখে সাথে সাথে বুক করতে পারেন। টিকিট ইস্যুর আগেই টাকা আপনার হাতে থাকে।")),
             ("ul", [T("Review limits monthly using the aging report", "এজিং রিপোর্ট দেখে প্রতি মাসে লিমিট পর্যালোচনা করুন"),
                     T("Share statements so agents see their balance", "স্টেটমেন্ট শেয়ার করুন যাতে এজেন্টরা ব্যালান্স দেখতে পান"),
                     T("Reward fast payers with higher limits", "দ্রুত পরিশোধকারীদের বেশি লিমিট দিন")]),
         ]),
    dict(slug="double-entry-accounting-travel", cat="Finance", icon="i-wallet", color="#7a3e12",
         date=T("15 September 2026", "১৫ সেপ্টেম্বর ২০২৬"), read=7,
         title=T("Why travel agencies need double-entry accounting", "ট্রাভেল এজেন্সির কেন ডাবল-এন্ট্রি অ্যাকাউন্টিং দরকার"),
         excerpt=T("Sales are not profit. Learn how proper ledgers show what you really earn on every booking.", "বিক্রি মানেই মুনাফা নয়। সঠিক লেজার কীভাবে প্রতিটি বুকিংয়ে আসল আয় দেখায় জেনে নিন।"),
         body=[
             ("p", T("Travel agencies move large amounts of money that are not theirs: fares owed to airlines, hotel costs, visa fees. A simple cash book cannot tell you how much of the money in the bank is actually profit.",
                     "ট্রাভেল এজেন্সির হাত দিয়ে অনেক টাকা যায় যা আসলে তাদের নয়: এয়ারলাইনের পাওনা ভাড়া, হোটেলের খরচ, ভিসা ফি। সাধারণ ক্যাশ বুক বলতে পারে না ব্যাংকের টাকার কতটা আসলে মুনাফা।")),
             ("h2", T("Every booking has two sides", "প্রতিটি বুকিংয়ের দুটি দিক")),
             ("p", T("When you sell a ticket, the customer or agent owes you, and you owe the airline. Double-entry accounting records both, so receivables and payables are always correct.",
                     "আপনি যখন টিকিট বিক্রি করেন, কাস্টমার বা এজেন্ট আপনার কাছে ঋণী হন, আর আপনি এয়ারলাইনের কাছে। ডাবল-এন্ট্রি অ্যাকাউন্টিং দুটোই রেকর্ড করে, তাই প্রাপ্য ও দেনা সবসময় সঠিক থাকে।")),
             ("h2", T("Profit per booking, not per month", "মাসে নয়, প্রতি বুকিংয়ে মুনাফা")),
             ("p", T("With service fees, markups and costs recorded per booking, you can see which services, agents and staff really make money.",
                     "সার্ভিস ফি, মার্কআপ ও খরচ প্রতি বুকিংয়ে রেকর্ড হলে দেখা যায় কোন সার্ভিস, এজেন্ট ও স্টাফ আসলে আয় করছে।")),
             ("ul", [T("Know exactly what you owe each supplier", "প্রতিটি সাপ্লায়ারের কাছে ঠিক কত দেনা জানুন"),
                     T("Collect agent dues before they age", "বকেয়া পুরনো হওয়ার আগেই এজেন্টদের কাছ থেকে আদায় করুন"),
                     T("Close the month in a day, not a week", "সপ্তাহ নয়, এক দিনে মাস শেষ করুন")]),
         ]),
    dict(slug="whatsapp-for-travel-agencies", cat="Omnichannel", icon="i-chat", color="#0f5c4f",
         date=T("5 September 2026", "৫ সেপ্টেম্বর ২০২৬"), read=5,
         title=T("WhatsApp for travel agencies: turning chats into bookings", "ট্রাভেল এজেন্সির জন্য WhatsApp: চ্যাটকে বুকিংয়ে রূপ দিন"),
         excerpt=T("Most travel inquiries now start on WhatsApp. A shared inbox makes sure none of them are lost.", "এখন বেশিরভাগ ট্রাভেল ইনকোয়ারি শুরু হয় WhatsApp-এ। শেয়ার্ড ইনবক্স নিশ্চিত করে কোনোটাই হারাবে না।"),
         body=[
             ("p", T("Customers message the number they see on your Facebook page or website, often late at night. If that number lives on one staff member's phone, inquiries are lost when they are busy or away.",
                     "কাস্টমাররা আপনার Facebook পেজ বা ওয়েবসাইটে যে নম্বর দেখেন সেখানেই মেসেজ দেন, প্রায়ই গভীর রাতে। সেই নম্বর যদি একজন স্টাফের ফোনে থাকে, তিনি ব্যস্ত বা ছুটিতে থাকলে ইনকোয়ারি হারিয়ে যায়।")),
             ("h2", T("One number, the whole team", "একটি নম্বর, পুরো টিম")),
             ("p", T("A shared inbox lets several staff answer from the same WhatsApp Business number, with each conversation assigned to one person.",
                     "শেয়ার্ড ইনবক্সে কয়েকজন স্টাফ একই WhatsApp Business নম্বর থেকে উত্তর দিতে পারেন, আর প্রতিটি কথোপকথন একজনকে দায়িত্ব দেওয়া থাকে।")),
             ("h2", T("From chat to CRM", "চ্যাট থেকে CRM")),
             ("p", T("Turn a promising chat into a lead with one click. The conversation stays attached, so whoever follows up knows exactly what was discussed.",
                     "সম্ভাবনাময় চ্যাটকে এক ক্লিকে লিডে রূপ দিন। কথোপকথন যুক্ত থাকে, তাই যিনি ফলো-আপ করবেন তিনি জানেন ঠিক কী আলোচনা হয়েছিল।")),
             ("ul", [T("Use saved replies for common questions", "সাধারণ প্রশ্নের জন্য সংরক্ষিত রিপ্লাই ব্যবহার করুন"),
                     T("Let AI answer after office hours", "অফিস সময়ের পরে AI-কে উত্তর দিতে দিন"),
                     T("Measure response time per staff", "প্রতি স্টাফের উত্তর দেওয়ার সময় মাপুন")]),
         ]),
    dict(slug="ai-trip-planners", cat="AI", icon="i-bot", color="#3c2a7a",
         date=T("27 August 2026", "২৭ আগস্ট ২০২৬"), read=4,
         title=T("AI trip planners: what they can and can't do for your agency", "AI ট্রিপ প্ল্যানার: আপনার এজেন্সির জন্য কী পারে আর কী পারে না"),
         excerpt=T("AI can draft itineraries in seconds. Here is how to use it without losing the human touch.", "AI সেকেন্ডে ভ্রমণসূচির খসড়া তৈরি করতে পারে। মানুষের ছোঁয়া না হারিয়ে কীভাবে ব্যবহার করবেন দেখুন।"),
         body=[
             ("p", T("AI trip planners can turn a short request like five days in Bali for a family into a complete draft itinerary in seconds. That saves your team hours every week.",
                     "AI ট্রিপ প্ল্যানার ‘পরিবারের জন্য বালিতে পাঁচ দিন’-এর মতো ছোট অনুরোধকে সেকেন্ডে পূর্ণ ভ্রমণসূচির খসড়ায় রূপ দিতে পারে। এতে আপনার টিমের প্রতি সপ্তাহে অনেক ঘণ্টা বাঁচে।")),
             ("h2", T("What AI does well", "AI যা ভালো পারে")),
             ("ul", [T("Drafting day-by-day itineraries", "দিনভিত্তিক ভ্রমণসূচির খসড়া"),
                     T("Answering common questions instantly", "সাধারণ প্রশ্নের সাথে সাথে উত্তর"),
                     T("Qualifying leads by budget and dates", "বাজেট ও তারিখ দিয়ে লিড যাচাই")]),
             ("h2", T("Where your team still matters", "যেখানে এখনও আপনার টিম জরুরি")),
             ("p", T("Pricing, supplier choice and special requests still need your experience. Use AI for the first draft and let your consultants refine and confirm it.",
                     "মূল্য নির্ধারণ, সাপ্লায়ার বাছাই ও বিশেষ অনুরোধে এখনও আপনার অভিজ্ঞতা দরকার। প্রথম খসড়ার জন্য AI ব্যবহার করুন, আর আপনার কনসালট্যান্টরা তা ঠিকঠাক করে নিশ্চিত করুন।")),
         ]),
    dict(slug="choosing-a-travel-erp", cat="Guides", icon="i-tasks", color="#5a1f3c",
         date=T("18 August 2026", "১৮ আগস্ট ২০২৬"), read=6,
         title=T("Checklist: choosing the right travel ERP for your agency", "চেকলিস্ট: আপনার এজেন্সির জন্য সঠিক ট্রাভেল ERP বাছাই"),
         excerpt=T("Ten questions to ask any vendor before you move your agency to a new system.", "নতুন সিস্টেমে যাওয়ার আগে যেকোনো ভেন্ডরকে যে দশটি প্রশ্ন করবেন।"),
         body=[
             ("p", T("Switching systems is a big decision. The right travel ERP saves time every day; the wrong one creates double work. Use this checklist when you compare options.",
                     "সিস্টেম বদলানো বড় সিদ্ধান্ত। সঠিক ট্রাভেল ERP প্রতিদিন সময় বাঁচায়; ভুলটি দ্বিগুণ কাজ তৈরি করে। বিকল্পগুলো তুলনা করার সময় এই চেকলিস্ট ব্যবহার করুন।")),
             ("h2", T("Questions to ask", "যে প্রশ্নগুলো করবেন")),
             ("ul", [T("Does it handle every service you sell, including Hajj & Umrah?", "হজ ও উমরাহসহ আপনার বিক্রি করা প্রতিটি সার্ভিস কি সামলায়?"),
                     T("Do bookings post to accounts automatically?", "বুকিং কি অটোমেটিক হিসাবে পোস্ট হয়?"),
                     T("Is there a B2B portal with credit limits?", "ক্রেডিট লিমিটসহ B2B পোর্টাল আছে কি?"),
                     T("Does it support bKash, Nagad and local banks?", "বিকাশ, নগদ ও দেশীয় ব্যাংক সাপোর্ট করে কি?"),
                     T("Can staff use it in Bangla?", "স্টাফরা কি বাংলায় ব্যবহার করতে পারবেন?"),
                     T("Are WhatsApp and Messenger connected?", "WhatsApp ও Messenger যুক্ত কি?"),
                     T("Who imports your existing data?", "আপনার বর্তমান ডেটা কে ইমপোর্ট করবে?"),
                     T("Is training included?", "ট্রেনিং কি অন্তর্ভুক্ত?"),
                     T("Can you host it on your own server?", "নিজের সার্ভারে হোস্ট করা যাবে কি?"),
                     T("How fast does support respond?", "সাপোর্ট কত দ্রুত সাড়া দেয়?")]),
             ("p", T("Ask for a demo with your own workflows, not a generic tour. It is the fastest way to see whether a system fits.",
                     "সাধারণ ট্যুর নয়, নিজের কাজের ধরন দিয়ে ডেমো চান। কোনো সিস্টেম মানানসই কিনা দেখার এটাই দ্রুততম উপায়।")),
         ]),
]

# ---------------------------------------------------------------------------
# Legal pages
# ---------------------------------------------------------------------------
LEGAL = [
    dict(slug="terms", title=T("Terms & Conditions", "শর্তাবলি"),
         intro=T("These terms govern your use of the TravelSuite ERP website, software and services. By using them you agree to these terms.",
                 "এই শর্তাবলি TravelSuite ERP-এর ওয়েবসাইট, সফটওয়্যার ও সেবা ব্যবহারের ক্ষেত্রে প্রযোজ্য। এগুলো ব্যবহার করে আপনি এই শর্তাবলিতে সম্মত হচ্ছেন।"),
         sections=[
             (T("1. Our services", "১. আমাদের সেবা"),
              [T("TravelSuite ERP provides travel booking, ERP, website, AI automation and messaging software to travel businesses, either as a hosted cloud service or as a self-hosted license.",
                 "TravelSuite ERP ট্রাভেল ব্যবসার জন্য বুকিং, ERP, ওয়েবসাইট, AI অটোমেশন ও মেসেজিং সফটওয়্যার দেয়, ক্লাউড সার্ভিস অথবা নিজস্ব সার্ভারের লাইসেন্স হিসেবে।")]),
             (T("2. Accounts", "২. অ্যাকাউন্ট"),
              [T("You are responsible for keeping your login details secure and for all activity under your account. Tell us immediately if you suspect unauthorised access.",
                 "আপনার লগইন তথ্য নিরাপদ রাখা এবং আপনার অ্যাকাউন্টের সব কার্যক্রমের দায়িত্ব আপনার। অননুমোদিত প্রবেশের সন্দেহ হলে সাথে সাথে আমাদের জানান।")]),
             (T("3. Fees and payment", "৩. ফি ও পেমেন্ট"),
              [T("Subscription fees are billed monthly or yearly in advance. License fees are paid once before installation. Prices exclude VAT and third-party supplier fees unless stated otherwise.",
                 "সাবস্ক্রিপশন ফি মাসিক বা বার্ষিক অগ্রিম বিল করা হয়। লাইসেন্স ফি ইনস্টলেশনের আগে একবার পরিশোধ করতে হয়। উল্লেখ না থাকলে মূল্যে ভ্যাট ও তৃতীয় পক্ষের সাপ্লায়ার ফি অন্তর্ভুক্ত নয়।")]),
             (T("4. Your data", "৪. আপনার ডেটা"),
              [T("You own the data you enter into TravelSuite ERP. We process it only to provide the service, as described in our Privacy Policy.",
                 "TravelSuite ERP-এ আপনি যে ডেটা দেন তার মালিক আপনি। আমরা শুধু সেবা দেওয়ার জন্য তা ব্যবহার করি, যেমনটি গোপনীয়তা নীতিতে বলা আছে।")]),
             (T("5. Acceptable use", "৫. গ্রহণযোগ্য ব্যবহার"),
              [T("You must not use the service for unlawful activity, to send spam, or to attempt to access other customers' data or our systems without permission.",
                 "বেআইনি কাজে, স্প্যাম পাঠাতে, বা অনুমতি ছাড়া অন্য গ্রাহকের ডেটা বা আমাদের সিস্টেমে প্রবেশের চেষ্টায় এই সেবা ব্যবহার করা যাবে না।")]),
             (T("6. Third-party suppliers", "৬. তৃতীয় পক্ষের সাপ্লায়ার"),
              [T("Airline, hotel, payment and messaging providers are governed by your own agreements with them. We are not responsible for their availability, pricing or decisions.",
                 "এয়ারলাইন, হোটেল, পেমেন্ট ও মেসেজিং প্রোভাইডারদের সাথে আপনার নিজস্ব চুক্তি প্রযোজ্য। তাদের প্রাপ্যতা, মূল্য বা সিদ্ধান্তের জন্য আমরা দায়ী নই।")]),
             (T("7. Availability and support", "৭. প্রাপ্যতা ও সাপোর্ট"),
              [T("We aim to keep cloud services available at all times and to announce planned maintenance in advance. Support is provided during office hours through WhatsApp, phone and email.",
                 "আমরা ক্লাউড সেবা সবসময় চালু রাখার চেষ্টা করি এবং পরিকল্পিত রক্ষণাবেক্ষণ আগে থেকে জানাই। অফিস সময়ে WhatsApp, ফোন ও ইমেইলে সাপোর্ট দেওয়া হয়।")]),
             (T("8. Termination", "৮. সেবা বন্ধ"),
              [T("You may cancel at any time; the service continues until the end of the paid period. We may suspend accounts that breach these terms or remain unpaid.",
                 "আপনি যেকোনো সময় বাতিল করতে পারেন; পরিশোধিত সময়ের শেষ পর্যন্ত সেবা চলবে। এই শর্ত ভঙ্গ করলে বা বকেয়া থাকলে আমরা অ্যাকাউন্ট স্থগিত করতে পারি।")]),
             (T("9. Changes and governing law", "৯. পরিবর্তন ও প্রযোজ্য আইন"),
              [T("We may update these terms and will notify customers of material changes. These terms are governed by the laws of Bangladesh.",
                 "আমরা এই শর্তাবলি হালনাগাদ করতে পারি এবং গুরুত্বপূর্ণ পরিবর্তন গ্রাহকদের জানাব। এই শর্তাবলি বাংলাদেশের আইন অনুযায়ী পরিচালিত।")]),
         ]),
    dict(slug="privacy", title=T("Privacy Policy", "গোপনীয়তা নীতি"),
         intro=T("This policy explains what information TravelSuite ERP collects, how we use it and the choices you have.",
                 "TravelSuite ERP কী তথ্য সংগ্রহ করে, কীভাবে ব্যবহার করে এবং আপনার কী কী সুযোগ আছে, এই নীতিতে তা ব্যাখ্যা করা হয়েছে।"),
         sections=[
             (T("1. Information we collect", "১. আমরা যে তথ্য সংগ্রহ করি"),
              [T("Contact details you share with us, such as name, agency name, email and phone number.", "আপনার দেওয়া যোগাযোগের তথ্য, যেমন নাম, এজেন্সির নাম, ইমেইল ও ফোন নম্বর।"),
               T("Account and billing information for customers of our service.", "আমাদের সেবার গ্রাহকদের অ্যাকাউন্ট ও বিলিং তথ্য।"),
               T("Basic usage data such as pages visited and device type, used to improve the website.", "ওয়েবসাইট উন্নত করতে ব্যবহৃত সাধারণ ব্যবহারের তথ্য, যেমন দেখা পেজ ও ডিভাইসের ধরন।")]),
             (T("2. How we use information", "২. তথ্য যেভাবে ব্যবহার করি"),
              [T("To respond to demo requests and questions, provide and support the service, send invoices and important notices, and improve our products.",
                 "ডেমোর অনুরোধ ও প্রশ্নের উত্তর দিতে, সেবা দিতে ও সাপোর্ট করতে, ইনভয়েস ও জরুরি নোটিস পাঠাতে এবং প্রোডাক্ট উন্নত করতে।")]),
             (T("3. Your customers' data", "৩. আপনার কাস্টমারদের ডেটা"),
              [T("Data about your travellers, agents and suppliers that you store in TravelSuite ERP belongs to you. We process it only on your instructions and never sell it.",
                 "TravelSuite ERP-এ আপনার রাখা যাত্রী, এজেন্ট ও সাপ্লায়ারের ডেটা আপনার। আমরা শুধু আপনার নির্দেশে তা ব্যবহার করি এবং কখনো বিক্রি করি না।")]),
             (T("4. Sharing", "৪. তথ্য শেয়ার"),
              [T("We share information only with service providers who help us run the service, such as hosting and messaging providers, and when required by law.",
                 "আমরা শুধু সেবা চালাতে সহায়তাকারী প্রোভাইডারদের সাথে (যেমন হোস্টিং ও মেসেজিং) এবং আইনের প্রয়োজনে তথ্য শেয়ার করি।")]),
             (T("5. Security and retention", "৫. নিরাপত্তা ও সংরক্ষণ"),
              [T("We use encryption, access controls and daily backups to protect data. We keep information only as long as needed for the purposes above or as required by law.",
                 "ডেটা রক্ষায় আমরা এনক্রিপশন, অ্যাক্সেস নিয়ন্ত্রণ ও দৈনিক ব্যাকআপ ব্যবহার করি। উপরের উদ্দেশ্যে বা আইনের প্রয়োজনে যতদিন দরকার, শুধু ততদিন তথ্য রাখি।")]),
             (T("6. Your choices", "৬. আপনার সুযোগ"),
              [T("You can ask us to access, correct or delete your personal information, or to stop sending marketing messages, by contacting us on WhatsApp.",
                 "WhatsApp-এ যোগাযোগ করে আপনি আপনার ব্যক্তিগত তথ্য দেখতে, সংশোধন বা মুছে ফেলতে, অথবা মার্কেটিং মেসেজ বন্ধ করতে অনুরোধ করতে পারেন।")]),
         ]),
    dict(slug="refund", title=T("Refund Policy", "রিফান্ড নীতি"),
         intro=T("We want you to be confident in choosing TravelSuite ERP. This policy explains when refunds are available.",
                 "আমরা চাই আপনি নিশ্চিন্তে TravelSuite ERP বেছে নিন। কখন রিফান্ড পাওয়া যায়, এই নীতিতে তা ব্যাখ্যা করা হয়েছে।"),
         sections=[
             (T("1. Cloud subscriptions", "১. ক্লাউড সাবস্ক্রিপশন"),
              [T("Monthly plans can be cancelled at any time and are not refunded for the current month. Yearly plans cancelled within 14 days of the first payment receive a full refund, minus any setup work already delivered.",
                 "মাসিক প্ল্যান যেকোনো সময় বাতিল করা যায়, চলতি মাসের টাকা ফেরত দেওয়া হয় না। প্রথম পেমেন্টের ১৪ দিনের মধ্যে বার্ষিক প্ল্যান বাতিল করলে পূর্ণ রিফান্ড দেওয়া হয়, তবে ইতিমধ্যে করা সেটআপের খরচ বাদ যাবে।")]),
             (T("2. Lifetime licenses", "২. লাইফটাইম লাইসেন্স"),
              [T("Lifetime licenses can be refunded within 7 days of payment if installation has not started. After installation, licenses are not refundable.",
                 "ইনস্টলেশন শুরু না হলে পেমেন্টের ৭ দিনের মধ্যে লাইফটাইম লাইসেন্সের রিফান্ড পাওয়া যায়। ইনস্টলেশনের পরে লাইসেন্স রিফান্ডযোগ্য নয়।")]),
             (T("3. Add-ons and custom work", "৩. অ্যাড-অন ও কাস্টম কাজ"),
              [T("Supplier integrations, mobile apps and custom development are quoted separately. Work already completed is not refundable.",
                 "সাপ্লায়ার ইন্টিগ্রেশন, মোবাইল অ্যাপ ও কাস্টম ডেভেলপমেন্টের কোটেশন আলাদা। ইতিমধ্যে সম্পন্ন কাজ রিফান্ডযোগ্য নয়।")]),
             (T("4. Third-party fees", "৪. তৃতীয় পক্ষের ফি"),
              [T("Fees paid to GDS, airline, hotel, payment gateway or messaging providers are set by those providers and are not refunded by us.",
                 "GDS, এয়ারলাইন, হোটেল, পেমেন্ট গেটওয়ে বা মেসেজিং প্রোভাইডারকে দেওয়া ফি তারাই নির্ধারণ করে, আমরা তা ফেরত দিই না।")]),
             (T("5. How to request a refund", "৫. কীভাবে রিফান্ডের অনুরোধ করবেন"),
              [T("Message us on WhatsApp with your agency name and invoice number. Approved refunds are paid to the original payment method within 10 working days.",
                 "আপনার এজেন্সির নাম ও ইনভয়েস নম্বরসহ WhatsApp-এ মেসেজ দিন। অনুমোদিত রিফান্ড ১০ কর্মদিবসের মধ্যে মূল পেমেন্ট মাধ্যমে ফেরত দেওয়া হয়।")]),
         ]),
]
